/**
 * bar_trans_patch.js
 * ---------------------------------------------------------------
 * Extends BAR_TRANS with all 30 extra languages.
 * Includes: single Caffè D'Orzo / Ginseng (no Piccolo/Grande),
 * single Succo di Frutta (flavor picked via popup), Ricard, Whiskey.
 * Paste this AFTER the existing BAR_TRANS / BAR_ITEMS block.
 * ---------------------------------------------------------------
 */
(function () {
  var PATCH = {
    'nl': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Cafeïnevrije Koffie',
      'Caffè D\'Orzo': 'Gerstenkoffie',
      'Caffè Ginseng': 'Ginsengkoffie',
      'Caffè Corretto': 'Koffie met Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Warme Thee',
      'Infusi': 'Kruidenthee',
      'Cioccolata Calda': 'Warme Chocolade',
      'Acqua Naturale 1 lt': 'Plat Water 1 lt',
      'Acqua Gassata 1 lt': 'Bruisend Water 1 lt',
      'Estathé Limone': 'Ijsthee Citroen',
      'Estathé Pesca': 'Ijsthee Perzik',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citroen',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Vruchtensap',
      'Birra Bottiglia 33 cl': 'Fles Bier 33 cl',
      'Digestivi': 'Digestieven',
      'Distillati': 'Gedistilleerde Dranken',
      'Shot Alcolici': 'Alcoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citroen'
    },
    'es': {
      'Caffè Espresso': 'Café Espresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      'Caffè D\'Orzo': 'Café de Cebada',
      'Caffè Ginseng': 'Café de Ginseng',
      'Caffè Corretto': 'Café con Grappa',
      'Caffè Latte': 'Café con Leche',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Té Caliente',
      'Infusi': 'Infusiones',
      'Cioccolata Calda': 'Chocolate Caliente',
      'Acqua Naturale 1 lt': 'Agua Sin Gas 1 lt',
      'Acqua Gassata 1 lt': 'Agua Con Gas 1 lt',
      'Estathé Limone': 'Té Frío Limón',
      'Estathé Pesca': 'Té Frío Melocotón',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Zumo de Frutas',
      'Birra Bottiglia 33 cl': 'Cerveza Botella 33 cl',
      'Digestivi': 'Digestivos',
      'Distillati': 'Destilados',
      'Shot Alcolici': 'Chupitos',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Ron & Cola',
      'Gin Tonic': 'Gin Tónic',
      'Gin Lemon': 'Gin Limón'
    },
    'pt': {
      'Caffè Espresso': 'Café Expresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      'Caffè D\'Orzo': 'Café de Cevada',
      'Caffè Ginseng': 'Café de Ginseng',
      'Caffè Corretto': 'Café com Grappa',
      'Caffè Latte': 'Café com Leite',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Chá Quente',
      'Infusi': 'Infusões',
      'Cioccolata Calda': 'Chocolate Quente',
      'Acqua Naturale 1 lt': 'Água Sem Gás 1 lt',
      'Acqua Gassata 1 lt': 'Água Com Gás 1 lt',
      'Estathé Limone': 'Chá Frio Limão',
      'Estathé Pesca': 'Chá Frio Pêssego',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limão',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sumo de Fruta',
      'Birra Bottiglia 33 cl': 'Cerveja Garrafa 33 cl',
      'Digestivi': 'Digestivos',
      'Distillati': 'Destilados',
      'Shot Alcolici': 'Shots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tónico',
      'Gin Lemon': 'Gin Limão'
    },
    'ru': {
      'Caffè Espresso': 'Кофе Эспрессо',
      'Caffè Decaffeinato': 'Кофе без Кофеина',
      'Caffè D\'Orzo': 'Ячменный Кофе',
      'Caffè Ginseng': 'Женьшеневый Кофе',
      'Caffè Corretto': 'Кофе с Граппой',
      'Caffè Latte': 'Кофе Латте',
      'Latte Macchiato': 'Латте Макиато',
      'Thè Caldo': 'Горячий Чай',
      'Infusi': 'Травяной Чай',
      'Cioccolata Calda': 'Горячий Шоколад',
      'Acqua Naturale 1 lt': 'Негазированная Вода 1 л',
      'Acqua Gassata 1 lt': 'Газированная Вода 1 л',
      'Estathé Limone': 'Холодный Чай Лимон',
      'Estathé Pesca': 'Холодный Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Фруктовый Сок',
      'Birra Bottiglia 33 cl': 'Пиво в Бутылке 33 кл',
      'Digestivi': 'Дижестивы',
      'Distillati': 'Дистилляты',
      'Shot Alcolici': 'Алкогольные Шоты',
      'Ricard': 'Рикар',
      'Whiskey': 'Виски',
      'Whisky & Coca': 'Виски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тоник',
      'Gin Lemon': 'Джин & Лимон'
    },
    'pl': {
      'Caffè Espresso': 'Kawa Espresso',
      'Caffè Decaffeinato': 'Kawa Bezkofeinowa',
      'Caffè D\'Orzo': 'Kawa Jęczmienna',
      'Caffè Ginseng': 'Kawa Żeńszeniowa',
      'Caffè Corretto': 'Kawa z Grappą',
      'Caffè Latte': 'Kawa Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Gorąca Herbata',
      'Infusi': 'Herbaty Ziołowe',
      'Cioccolata Calda': 'Gorąca Czekolada',
      'Acqua Naturale 1 lt': 'Woda Niegazowana 1 lt',
      'Acqua Gassata 1 lt': 'Woda Gazowana 1 lt',
      'Estathé Limone': 'Mrożona Herbata Cytrynowa',
      'Estathé Pesca': 'Mrożona Herbata Brzoskwiniowa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Cytryna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sok Owocowy',
      'Birra Bottiglia 33 cl': 'Piwo Butelkowe 33 cl',
      'Digestivi': 'Digestify',
      'Distillati': 'Destylaty',
      'Shot Alcolici': 'Shoty Alkoholowe',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Cytryna'
    },
    'uk': {
      'Caffè Espresso': 'Кава Еспресо',
      'Caffè Decaffeinato': 'Кава без Кофеїну',
      'Caffè D\'Orzo': 'Ячмінна Кава',
      'Caffè Ginseng': 'Женьшенева Кава',
      'Caffè Corretto': 'Кава з Граппою',
      'Caffè Latte': 'Кава Латте',
      'Latte Macchiato': 'Латте Макіато',
      'Thè Caldo': 'Гарячий Чай',
      'Infusi': 'Трав\'яний Чай',
      'Cioccolata Calda': 'Гарячий Шоколад',
      'Acqua Naturale 1 lt': 'Негазована Вода 1 л',
      'Acqua Gassata 1 lt': 'Газована Вода 1 л',
      'Estathé Limone': 'Холодний Чай Лимон',
      'Estathé Pesca': 'Холодний Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Фруктовий Сік',
      'Birra Bottiglia 33 cl': 'Пиво в Пляшці 33 кл',
      'Digestivi': 'Дижестиви',
      'Distillati': 'Дистиляти',
      'Shot Alcolici': 'Алкогольні Шоти',
      'Ricard': 'Рікар',
      'Whiskey': 'Віскі',
      'Whisky & Coca': 'Віскі & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тонік',
      'Gin Lemon': 'Джин & Лимон'
    },
    'ro': {
      'Caffè Espresso': 'Cafea Espresso',
      'Caffè Decaffeinato': 'Cafea Decofeinizată',
      'Caffè D\'Orzo': 'Cafea de Orz',
      'Caffè Ginseng': 'Cafea de Ginseng',
      'Caffè Corretto': 'Cafea cu Grappa',
      'Caffè Latte': 'Cafea Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Ceai Cald',
      'Infusi': 'Infuzii',
      'Cioccolata Calda': 'Ciocolată Caldă',
      'Acqua Naturale 1 lt': 'Apă Plată 1 lt',
      'Acqua Gassata 1 lt': 'Apă Carbogazoasă 1 lt',
      'Estathé Limone': 'Ceai Rece Lămâie',
      'Estathé Pesca': 'Ceai Rece Piersică',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Lămâie',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Suc de Fructe',
      'Birra Bottiglia 33 cl': 'Bere Sticlă 33 cl',
      'Digestivi': 'Digestive',
      'Distillati': 'Distilate',
      'Shot Alcolici': 'Shoturi Alcoolice',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin Tonic',
      'Gin Lemon': 'Gin Lămâie'
    },
    'sv': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfritt Kaffe',
      'Caffè D\'Orzo': 'Kornkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varmt Te',
      'Infusi': 'Örtte',
      'Cioccolata Calda': 'Varm Choklad',
      'Acqua Naturale 1 lt': 'Stilla Vatten 1 lt',
      'Acqua Gassata 1 lt': 'Kolsyrat Vatten 1 lt',
      'Estathé Limone': 'Iste Citron',
      'Estathé Pesca': 'Iste Persika',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Fruktjuice',
      'Birra Bottiglia 33 cl': 'Flasköl 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillat',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    'da': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      'Caffè D\'Orzo': 'Bygkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varm Te',
      'Infusi': 'Urtethe',
      'Cioccolata Calda': 'Varm Chokolade',
      'Acqua Naturale 1 lt': 'Stille Vand 1 lt',
      'Acqua Gassata 1 lt': 'Kulsyreholdigt Vand 1 lt',
      'Estathé Limone': 'Isite Citron',
      'Estathé Pesca': 'Isite Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Frugtjuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillater',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    'no': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      'Caffè D\'Orzo': 'Byggkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varm Te',
      'Infusi': 'Urtete',
      'Cioccolata Calda': 'Varm Sjokolade',
      'Acqua Naturale 1 lt': 'Stille Vann 1 lt',
      'Acqua Gassata 1 lt': 'Kullsyreholdig Vann 1 lt',
      'Estathé Limone': 'Iste Sitron',
      'Estathé Pesca': 'Iste Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Fruktjuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillater',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitron'
    },
    'fi': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Kofeiiniton Kahvi',
      'Caffè D\'Orzo': 'Ohrakahvi',
      'Caffè Ginseng': 'Ginsengkahvi',
      'Caffè Corretto': 'Kahvi Grappalla',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Kuuma Tee',
      'Infusi': 'Yrttitee',
      'Cioccolata Calda': 'Kuuma Kaakao',
      'Acqua Naturale 1 lt': 'Hanavesi 1 lt',
      'Acqua Gassata 1 lt': 'Kivennäisvesi 1 lt',
      'Estathé Limone': 'Jäätee Sitruuna',
      'Estathé Pesca': 'Jäätee Persikka',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitruuna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Hedelmämehu',
      'Birra Bottiglia 33 cl': 'Olutpullo 33 cl',
      'Digestivi': 'Digestiivit',
      'Distillati': 'Väkevät Alkoholit',
      'Shot Alcolici': 'Alkoholishotteja',
      'Ricard': 'Ricard',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Cola',
      'Rhum & Coca': 'Rommi & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitruuna'
    },
    'el': {
      'Caffè Espresso': 'Καφές Εσπρέσο',
      'Caffè Decaffeinato': 'Καφές Ντεκαφεϊνέ',
      'Caffè D\'Orzo': 'Καφές Κριθαριού',
      'Caffè Ginseng': 'Καφές Τζίνσενγκ',
      'Caffè Corretto': 'Καφές με Γκράπα',
      'Caffè Latte': 'Καφές Λάτε',
      'Latte Macchiato': 'Λάτε Μακιάτο',
      'Thè Caldo': 'Ζεστό Τσάι',
      'Infusi': 'Αφεψήματα',
      'Cioccolata Calda': 'Ζεστή Σοκολάτα',
      'Acqua Naturale 1 lt': 'Φυσικό Νερό 1 lt',
      'Acqua Gassata 1 lt': 'Ανθρακούχο Νερό 1 lt',
      'Estathé Limone': 'Παγωμένο Τσάι Λεμόνι',
      'Estathé Pesca': 'Παγωμένο Τσάι Ροδάκινο',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Λεμόνι',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Χυμός Φρούτων',
      'Birra Bottiglia 33 cl': 'Μπύρα Μπουκάλι 33 cl',
      'Digestivi': 'Πεπτικά',
      'Distillati': 'Αποστάγματα',
      'Shot Alcolici': 'Σφηνάκια',
      'Ricard': 'Ρικάρ',
      'Whiskey': 'Ουίσκι',
      'Whisky & Coca': 'Ουίσκι & Κόλα',
      'Rhum & Coca': 'Ρούμι & Κόλα',
      'Gin Tonic': 'Τζιν Τόνικ',
      'Gin Lemon': 'Τζιν Λεμόνι'
    },
    'cs': {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      'Caffè D\'Orzo': 'Ječmenná Káva',
      'Caffè Ginseng': 'Ženšenová Káva',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Horký Čaj',
      'Infusi': 'Bylinné Čaje',
      'Cioccolata Calda': 'Horká Čokoláda',
      'Acqua Naturale 1 lt': 'Neperlivá Voda 1 lt',
      'Acqua Gassata 1 lt': 'Perlivá Voda 1 lt',
      'Estathé Limone': 'Ledový Čaj Citron',
      'Estathé Pesca': 'Ledový Čaj Broskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Ovocný Džus',
      'Birra Bottiglia 33 cl': 'Pivo v Láhvi 33 cl',
      'Digestivi': 'Digestivy',
      'Distillati': 'Destiláty',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citron'
    },
    'hu': {
      'Caffè Espresso': 'Eszpresszó',
      'Caffè Decaffeinato': 'Koffeinmentes Kávé',
      'Caffè D\'Orzo': 'Árpakávé',
      'Caffè Ginseng': 'Ginszeng Kávé',
      'Caffè Corretto': 'Kávé Grappával',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Meleg Tea',
      'Infusi': 'Gyógynövény Tea',
      'Cioccolata Calda': 'Forró Csokoládé',
      'Acqua Naturale 1 lt': 'Szénsavmentes Víz 1 lt',
      'Acqua Gassata 1 lt': 'Szénsavas Víz 1 lt',
      'Estathé Limone': 'Jeges Tea Citrom',
      'Estathé Pesca': 'Jeges Tea Barack',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrom',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Gyümölcslé',
      'Birra Bottiglia 33 cl': 'Üveges Sör 33 cl',
      'Digestivi': 'Digestifek',
      'Distillati': 'Desztillátumok',
      'Shot Alcolici': 'Alkoholos Shotok',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrom'
    },
    'bg': {
      'Caffè Espresso': 'Кафе Еспресо',
      'Caffè Decaffeinato': 'Безкофеиново Кафе',
      'Caffè D\'Orzo': 'Ечемично Кафе',
      'Caffè Ginseng': 'Женшеново Кафе',
      'Caffè Corretto': 'Кафе с Грапа',
      'Caffè Latte': 'Кафе Лате',
      'Latte Macchiato': 'Лате Макиато',
      'Thè Caldo': 'Горещ Чай',
      'Infusi': 'Билков Чай',
      'Cioccolata Calda': 'Горещ Шоколад',
      'Acqua Naturale 1 lt': 'Негазирана Вода 1 л',
      'Acqua Gassata 1 lt': 'Газирана Вода 1 л',
      'Estathé Limone': 'Студен Чай Лимон',
      'Estathé Pesca': 'Студен Чай Праскова',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Плодов Сок',
      'Birra Bottiglia 33 cl': 'Бутилирана Бира 33 кл',
      'Digestivi': 'Дижестиви',
      'Distillati': 'Дестилати',
      'Shot Alcolici': 'Алкохолни Шотове',
      'Ricard': 'Рикар',
      'Whiskey': 'Уиски',
      'Whisky & Coca': 'Уиски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин Тоник',
      'Gin Lemon': 'Джин Лимон'
    },
    'sk': {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      'Caffè D\'Orzo': 'Jačmenná Káva',
      'Caffè Ginseng': 'Ženšenová Káva',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Horúci Čaj',
      'Infusi': 'Bylinkové Čaje',
      'Cioccolata Calda': 'Horúca Čokoláda',
      'Acqua Naturale 1 lt': 'Neperlivá Voda 1 lt',
      'Acqua Gassata 1 lt': 'Perlivá Voda 1 lt',
      'Estathé Limone': 'Ľadový Čaj Citrón',
      'Estathé Pesca': 'Ľadový Čaj Broskyňa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Ovocný Džús',
      'Birra Bottiglia 33 cl': 'Fľaška Piva 33 cl',
      'Digestivi': 'Digestívy',
      'Distillati': 'Destiláty',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrón'
    },
    'hr': {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Kava bez Kofeina',
      'Caffè D\'Orzo': 'Ječmena Kava',
      'Caffè Ginseng': 'Ginzeng Kava',
      'Caffè Corretto': 'Kava s Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Voćni Sok',
      'Birra Bottiglia 33 cl': 'Pivo Boca 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Shotovi',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limun'
    },
    'sr': {
      'Caffè Espresso': 'Kafa Espreso',
      'Caffè Decaffeinato': 'Kafa bez Kofeina',
      'Caffè D\'Orzo': 'Ječmena Kafa',
      'Caffè Ginseng': 'Ginzeng Kafa',
      'Caffè Corretto': 'Kafa sa Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Voćni Sok',
      'Birra Bottiglia 33 cl': 'Pivo Flaša 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Šotovi',
      'Ricard': 'Rikar',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rum & Kola',
      'Gin Tonic': 'Džin Tonik',
      'Gin Lemon': 'Džin Limun'
    },
    'sl': {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Brezkofeinska Kava',
      'Caffè D\'Orzo': 'Ječmenova Kava',
      'Caffè Ginseng': 'Ginsenova Kava',
      'Caffè Corretto': 'Kava z Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topel Čaj',
      'Infusi': 'Zeliščni Čaj',
      'Cioccolata Calda': 'Vroča Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limona',
      'Estathé Pesca': 'Ledeni Čaj Breskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limona',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sadni Sok',
      'Birra Bottiglia 33 cl': 'Stekleničeno Pivo 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Shoti',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limona'
    },
    'tr': {
      'Caffè Espresso': 'Espresso Kahve',
      'Caffè Decaffeinato': 'Kafeinsiz Kahve',
      'Caffè D\'Orzo': 'Arpa Kahvesi',
      'Caffè Ginseng': 'Ginseng Kahvesi',
      'Caffè Corretto': 'Grappa\'lı Kahve',
      'Caffè Latte': 'Sütlü Kahve',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Sıcak Çay',
      'Infusi': 'Bitki Çayı',
      'Cioccolata Calda': 'Sıcak Çikolata',
      'Acqua Naturale 1 lt': 'Doğal Su 1 lt',
      'Acqua Gassata 1 lt': 'Gazlı Su 1 lt',
      'Estathé Limone': 'Soğuk Çay Limon',
      'Estathé Pesca': 'Soğuk Çay Şeftali',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limon',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Meyve Suyu',
      'Birra Bottiglia 33 cl': 'Şişe Bira 33 cl',
      'Digestivi': 'Digestifler',
      'Distillati': 'Damıtılmış İçkiler',
      'Shot Alcolici': 'Alkol Şotları',
      'Ricard': 'Ricard',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rom & Kola',
      'Gin Tonic': 'Cin Tonik',
      'Gin Lemon': 'Cin Limon'
    },
    'ar': {
      'Caffè Espresso': 'قهوة إسبريسو',
      'Caffè Decaffeinato': 'قهوة منزوعة الكافيين',
      'Caffè D\'Orzo': 'قهوة الشعير',
      'Caffè Ginseng': 'قهوة الجنسنغ',
      'Caffè Corretto': 'قهوة بالغراپا',
      'Caffè Latte': 'كافيه لاتيه',
      'Latte Macchiato': 'لاتيه ماكياتو',
      'Thè Caldo': 'شاي ساخن',
      'Infusi': 'شاي أعشاب',
      'Cioccolata Calda': 'شوكولاتة ساخنة',
      'Acqua Naturale 1 lt': 'مياه طبيعية 1 لتر',
      'Acqua Gassata 1 lt': 'مياه غازية 1 لتر',
      'Estathé Limone': 'شاي بارد بالليمون',
      'Estathé Pesca': 'شاي بارد بالخوخ',
      'Schweppes': 'شويبس',
      'Schweppes Lemon': 'شويبس ليمون',
      'Crodino': 'كرودينو',
      'Sanbitter': 'سانبيتر',
      'Succo di Frutta': 'عصير فواكه',
      'Birra Bottiglia 33 cl': 'بيرة زجاجة 33 سل',
      'Digestivi': 'مشروبات هضمية',
      'Distillati': 'مقطرات',
      'Shot Alcolici': 'شوتات كحولية',
      'Ricard': 'ريكار',
      'Whiskey': 'ويسكي',
      'Whisky & Coca': 'ويسكي & كولا',
      'Rhum & Coca': 'روم & كولا',
      'Gin Tonic': 'جن & توني',
      'Gin Lemon': 'جن & ليمون'
    },
    'zh-CN': {
      'Caffè Espresso': '意式浓缩咖啡',
      'Caffè Decaffeinato': '低咖啡因咖啡',
      'Caffè D\'Orzo': '大麦咖啡',
      'Caffè Ginseng': '人参咖啡',
      'Caffè Corretto': '格拉帕咖啡',
      'Caffè Latte': '拿铁咖啡',
      'Latte Macchiato': '玛奇朵',
      'Thè Caldo': '热茶',
      'Infusi': '花草茶',
      'Cioccolata Calda': '热巧克力',
      'Acqua Naturale 1 lt': '天然矿泉水 1升',
      'Acqua Gassata 1 lt': '气泡水 1升',
      'Estathé Limone': '柠檬冰茶',
      'Estathé Pesca': '桃子冰茶',
      'Schweppes': '施韦普斯',
      'Schweppes Lemon': '施韦普斯柠檬',
      'Crodino': '克罗迪诺',
      'Sanbitter': '桑比特',
      'Succo di Frutta': '果汁',
      'Birra Bottiglia 33 cl': '瓶装啤酒 33克拉',
      'Digestivi': '助消化饮品',
      'Distillati': '蒸馏酒',
      'Shot Alcolici': '烈酒一口杯',
      'Ricard': '力加',
      'Whiskey': '威士忌',
      'Whisky & Coca': '威士忌 & 可乐',
      'Rhum & Coca': '朗姆酒 & 可乐',
      'Gin Tonic': '金汤力',
      'Gin Lemon': '金柠檬'
    },
    'ja': {
      'Caffè Espresso': 'エスプレッソ',
      'Caffè Decaffeinato': 'デカフェコーヒー',
      'Caffè D\'Orzo': '大麦コーヒー',
      'Caffè Ginseng': '高麗人参コーヒー',
      'Caffè Corretto': 'グラッパ入りコーヒー',
      'Caffè Latte': 'カフェラテ',
      'Latte Macchiato': 'ラテマキアート',
      'Thè Caldo': 'ホットティー',
      'Infusi': 'ハーブティー',
      'Cioccolata Calda': 'ホットチョコレート',
      'Acqua Naturale 1 lt': 'ミネラルウォーター 1L',
      'Acqua Gassata 1 lt': '炭酸水 1L',
      'Estathé Limone': 'レモンアイスティー',
      'Estathé Pesca': '桃アイスティー',
      'Schweppes': 'シュウェップス',
      'Schweppes Lemon': 'シュウェップス レモン',
      'Crodino': 'クロディーノ',
      'Sanbitter': 'サンビター',
      'Succo di Frutta': 'フルーツジュース',
      'Birra Bottiglia 33 cl': 'ビール瓶 33cl',
      'Digestivi': '食後酒',
      'Distillati': '蒸留酒',
      'Shot Alcolici': 'アルコールショット',
      'Ricard': 'リカール',
      'Whiskey': 'ウイスキー',
      'Whisky & Coca': 'ウイスキー & コーラ',
      'Rhum & Coca': 'ラム & コーラ',
      'Gin Tonic': 'ジン & トニック',
      'Gin Lemon': 'ジン & レモン'
    },
    'ko': {
      'Caffè Espresso': '에스프레소',
      'Caffè Decaffeinato': '디카페인 커피',
      'Caffè D\'Orzo': '보리 커피',
      'Caffè Ginseng': '인삼 커피',
      'Caffè Corretto': '그라파 커피',
      'Caffè Latte': '카페 라테',
      'Latte Macchiato': '라테 마키아토',
      'Thè Caldo': '따뜻한 차',
      'Infusi': '허브티',
      'Cioccolata Calda': '핫 초콜릿',
      'Acqua Naturale 1 lt': '생수 1L',
      'Acqua Gassata 1 lt': '탄산수 1L',
      'Estathé Limone': '레몬 아이스티',
      'Estathé Pesca': '복숭아 아이스티',
      'Schweppes': '슈웹스',
      'Schweppes Lemon': '슈웹스 레몬',
      'Crodino': '크로디노',
      'Sanbitter': '산비터',
      'Succo di Frutta': '과일 주스',
      'Birra Bottiglia 33 cl': '병 맥주 33cl',
      'Digestivi': '소화 증진 주류',
      'Distillati': '증류주',
      'Shot Alcolici': '알코올 샷',
      'Ricard': '리카르',
      'Whiskey': '위스키',
      'Whisky & Coca': '위스키 & 콜라',
      'Rhum & Coca': '럼 & 콜라',
      'Gin Tonic': '진 토닉',
      'Gin Lemon': '진 레몬'
    },
    'hi': {
      'Caffè Espresso': 'एस्प्रेसो कॉफ़ी',
      'Caffè Decaffeinato': 'डिकैफ़ कॉफ़ी',
      'Caffè D\'Orzo': 'जौ कॉफ़ी',
      'Caffè Ginseng': 'जिनसेंग कॉफ़ी',
      'Caffè Corretto': 'ग्रापा के साथ कॉफ़ी',
      'Caffè Latte': 'कैफ़े लाते',
      'Latte Macchiato': 'लाते मैकियाटो',
      'Thè Caldo': 'गर्म चाय',
      'Infusi': 'हर्बल चाय',
      'Cioccolata Calda': 'गर्म चॉकलेट',
      'Acqua Naturale 1 lt': 'सादा पानी 1 लीटर',
      'Acqua Gassata 1 lt': 'कार्बोनेटेड पानी 1 लीटर',
      'Estathé Limone': 'आइस्ड टी नींबू',
      'Estathé Pesca': 'आइस्ड टी आड़ू',
      'Schweppes': 'श्वेप्स',
      'Schweppes Lemon': 'श्वेप्स नींबू',
      'Crodino': 'क्रोदिनो',
      'Sanbitter': 'सैनबिटर',
      'Succo di Frutta': 'फलों का जूस',
      'Birra Bottiglia 33 cl': 'बीयर बोतल 33 cl',
      'Digestivi': 'पाचक पेय',
      'Distillati': 'डिस्टिल्ड शराब',
      'Shot Alcolici': 'अल्कोहल शॉट्स',
      'Ricard': 'रिकार',
      'Whiskey': 'व्हिस्की',
      'Whisky & Coca': 'व्हिस्की & कोला',
      'Rhum & Coca': 'रम & कोला',
      'Gin Tonic': 'जिन टॉनिक',
      'Gin Lemon': 'जिन नींबू'
    },
    'bn': {
      'Caffè Espresso': 'এস্প্রেসো কফি',
      'Caffè Decaffeinato': 'ডিক্যাফ কফি',
      'Caffè D\'Orzo': 'বার্লি কফি',
      'Caffè Ginseng': 'জিনসেং কফি',
      'Caffè Corretto': 'গ্রাপা সহ কফি',
      'Caffè Latte': 'ক্যাফে লাতে',
      'Latte Macchiato': 'লাতে মাকিয়াতো',
      'Thè Caldo': 'গরম চা',
      'Infusi': 'হার্বাল চা',
      'Cioccolata Calda': 'গরম চকোলেট',
      'Acqua Naturale 1 lt': 'সাদা পানি ১ লিটার',
      'Acqua Gassata 1 lt': 'কার্বনেটেড পানি ১ লিটার',
      'Estathé Limone': 'আইসড টি লেবু',
      'Estathé Pesca': 'আইসড টি পিচ',
      'Schweppes': 'শোয়েপস',
      'Schweppes Lemon': 'শোয়েপস লেবু',
      'Crodino': 'ক্রোদিনো',
      'Sanbitter': 'স্যানবিটার',
      'Succo di Frutta': 'ফলের জুস',
      'Birra Bottiglia 33 cl': 'বোতল বিয়ার ৩৩ ক্লি',
      'Digestivi': 'পাচক পানীয়',
      'Distillati': 'পাতিত মদ',
      'Shot Alcolici': 'অ্যালকোহল শট',
      'Ricard': 'রিকার্ড',
      'Whiskey': 'হুইস্কি',
      'Whisky & Coca': 'হুইস্কি & কোলা',
      'Rhum & Coca': 'রাম & কোলা',
      'Gin Tonic': 'জিন টনিক',
      'Gin Lemon': 'জিন লেবু'
    },
    'ur': {
      'Caffè Espresso': 'ایسپریسو کافی',
      'Caffè Decaffeinato': 'بغیر کیفین کافی',
      'Caffè D\'Orzo': 'جَو کافی',
      'Caffè Ginseng': 'جنسنگ کافی',
      'Caffè Corretto': 'گراپا کے ساتھ کافی',
      'Caffè Latte': 'کیفے لاتے',
      'Latte Macchiato': 'لاتے ماکیاتو',
      'Thè Caldo': 'گرم چائے',
      'Infusi': 'جڑی بوٹی چائے',
      'Cioccolata Calda': 'گرم چاکلیٹ',
      'Acqua Naturale 1 lt': 'سادہ پانی ۱ لیٹر',
      'Acqua Gassata 1 lt': 'کاربونیٹڈ پانی ۱ لیٹر',
      'Estathé Limone': 'آئسڈ ٹی لیموں',
      'Estathé Pesca': 'آئسڈ ٹی آڑو',
      'Schweppes': 'شوئپس',
      'Schweppes Lemon': 'شوئپس لیموں',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان بیٹر',
      'Succo di Frutta': 'پھلوں کا جوس',
      'Birra Bottiglia 33 cl': 'بوتل بیئر ۳۳ کل',
      'Digestivi': 'ہاضمہ مشروبات',
      'Distillati': 'ڈسٹل شراب',
      'Shot Alcolici': 'الکوہل شاٹ',
      'Ricard': 'ریکارڈ',
      'Whiskey': 'وسکی',
      'Whisky & Coca': 'وسکی & کولا',
      'Rhum & Coca': 'رم & کولا',
      'Gin Tonic': 'جن ٹانک',
      'Gin Lemon': 'جن لیموں'
    },
    'fa': {
      'Caffè Espresso': 'اسپرسو',
      'Caffè Decaffeinato': 'قهوه بدون کافئین',
      'Caffè D\'Orzo': 'قهوه جو',
      'Caffè Ginseng': 'قهوه جینسنگ',
      'Caffè Corretto': 'قهوه با گراپا',
      'Caffè Latte': 'کافه لاته',
      'Latte Macchiato': 'لاته ماکیاتو',
      'Thè Caldo': 'چای گرم',
      'Infusi': 'دمنوش گیاهی',
      'Cioccolata Calda': 'شکلات داغ',
      'Acqua Naturale 1 lt': 'آب معدنی ۱ لیتر',
      'Acqua Gassata 1 lt': 'آب گازدار ۱ لیتر',
      'Estathé Limone': 'چای سرد لیمو',
      'Estathé Pesca': 'چای سرد هلو',
      'Schweppes': 'شوپس',
      'Schweppes Lemon': 'شوپس لیمو',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان‌بیتر',
      'Succo di Frutta': 'آب میوه',
      'Birra Bottiglia 33 cl': 'آبجو بطری ۳۳ سی‌سی',
      'Digestivi': 'نوشیدنی گوارشی',
      'Distillati': 'مشروبات تقطیر شده',
      'Shot Alcolici': 'شات الکلی',
      'Ricard': 'ریکارد',
      'Whiskey': 'ویسکی',
      'Whisky & Coca': 'ویسکی & کولا',
      'Rhum & Coca': 'رام & کولا',
      'Gin Tonic': 'جین تونیک',
      'Gin Lemon': 'جین لیمون'
    },
    'vi': {
      'Caffè Espresso': 'Cà Phê Espresso',
      'Caffè Decaffeinato': 'Cà Phê Không Caffeine',
      'Caffè D\'Orzo': 'Cà Phê Lúa Mạch',
      'Caffè Ginseng': 'Cà Phê Nhân Sâm',
      'Caffè Corretto': 'Cà Phê Pha Rượu Grappa',
      'Caffè Latte': 'Cà Phê Sữa',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Trà Nóng',
      'Infusi': 'Trà Thảo Mộc',
      'Cioccolata Calda': 'Sô Cô La Nóng',
      'Acqua Naturale 1 lt': 'Nước Lọc 1 lít',
      'Acqua Gassata 1 lt': 'Nước Có Ga 1 lít',
      'Estathé Limone': 'Trà Đá Chanh',
      'Estathé Pesca': 'Trà Đá Đào',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Chanh',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Nước Ép Trái Cây',
      'Birra Bottiglia 33 cl': 'Bia Chai 33 cl',
      'Digestivi': 'Rượu Tiêu Hóa',
      'Distillati': 'Rượu Chưng Cất',
      'Shot Alcolici': 'Shot Rượu',
      'Ricard': 'Ricard',
      'Whiskey': 'Whiskey',
      'Whisky & Coca': 'Whisky & Coca',
      'Rhum & Coca': 'Rum & Coca',
      'Gin Tonic': 'Gin Tonic',
      'Gin Lemon': 'Gin Chanh'
    },
    'th': {
      'Caffè Espresso': 'กาแฟเอสเปรสโซ',
      'Caffè Decaffeinato': 'กาแฟไร้คาเฟอีน',
      'Caffè D\'Orzo': 'กาแฟข้าวบาร์เลย์',
      'Caffè Ginseng': 'กาแฟโสม',
      'Caffè Corretto': 'กาแฟใส่กราปปา',
      'Caffè Latte': 'คาเฟ่ลาเต้',
      'Latte Macchiato': 'ลาเต้มัคคิอาโต้',
      'Thè Caldo': 'ชาร้อน',
      'Infusi': 'ชาสมุนไพร',
      'Cioccolata Calda': 'ช็อกโกแลตร้อน',
      'Acqua Naturale 1 lt': 'น้ำเปล่า 1 ลิตร',
      'Acqua Gassata 1 lt': 'น้ำอัดลม 1 ลิตร',
      'Estathé Limone': 'ชาเย็นมะนาว',
      'Estathé Pesca': 'ชาเย็นพีช',
      'Schweppes': 'ชเวปส์',
      'Schweppes Lemon': 'ชเวปส์มะนาว',
      'Crodino': 'โครดิโน',
      'Sanbitter': 'ซานบิทเทอร์',
      'Succo di Frutta': 'น้ำผลไม้',
      'Birra Bottiglia 33 cl': 'เบียร์ขวด 33 ซล.',
      'Digestivi': 'เครื่องดื่มช่วยย่อย',
      'Distillati': 'สุรากลั่น',
      'Shot Alcolici': 'ช็อตแอลกอฮอล์',
      'Ricard': 'ริการ์ด',
      'Whiskey': 'วิสกี้',
      'Whisky & Coca': 'วิสกี้ & โคล่า',
      'Rhum & Coca': 'รัม & โคล่า',
      'Gin Tonic': 'จิน โทนิค',
      'Gin Lemon': 'จิน มะนาว'
    }
  };

  // Merge into existing BAR_TRANS (correct axis: dish-name -> lang -> translation)
  if (typeof BAR_TRANS !== 'undefined') {
    var mergedCount = 0;
    Object.keys(PATCH).forEach(function (lang) {
      Object.keys(PATCH[lang]).forEach(function (dishName) {
        if (!BAR_TRANS[dishName]) BAR_TRANS[dishName] = {};
        BAR_TRANS[dishName][lang] = PATCH[lang][dishName];
        mergedCount++;
      });
    });
    console.log('[bar_trans_patch] Merged ' + mergedCount + ' dish translations across ' + Object.keys(PATCH).length + ' languages into BAR_TRANS.');
  } else {
    console.warn('[bar_trans_patch] BAR_TRANS not found — load this AFTER the BAR_TRANS block.');
  }

  // ------------------------------------------------------------
  // BAR_GROUP_TITLES — same 30 languages for the 3 section headers
  // ------------------------------------------------------------
  var GROUP_PATCH = {
    'nl': { birre: '🍺 Bieren & Basisaperitieven', spritz: '🥂 Spritz & Klassieke Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    'es': { birre: '🍺 Cervezas & Aperitivos Base', spritz: '🥂 Spritz & Cócteles Clásicos — €6,00', premium: '⭐ Cócteles Premium — €8,00' },
    'pt': { birre: '🍺 Cervejas & Aperitivos Base', spritz: '🥂 Spritz & Cocktails Clássicos — €6,00', premium: '⭐ Cocktails Premium — €8,00' },
    'ru': { birre: '🍺 Пиво и Базовые Аперитивы', spritz: '🥂 Спритц и Классические Коктейли — €6,00', premium: '⭐ Премиум Коктейли — €8,00' },
    'pl': { birre: '🍺 Piwa i Podstawowe Aperitify', spritz: '🥂 Spritz i Klasyczne Koktajle — €6,00', premium: '⭐ Koktajle Premium — €8,00' },
    'uk': { birre: '🍺 Пиво та Базові Аперитиви', spritz: '🥂 Спритц і Класичні Коктейлі — €6,00', premium: '⭐ Преміум Коктейлі — €6,00' },
    'ro': { birre: '🍺 Beri & Aperitive de Bază', spritz: '🥂 Spritz & Cocktailuri Clasice — €6,00', premium: '⭐ Cocktailuri Premium — €8,00' },
    'sv': { birre: '🍺 Öl & Grundaperitif', spritz: '🥂 Spritz & Klassiska Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    'da': { birre: '🍺 Øl & Grundaperitif', spritz: '🥂 Spritz & Klassiske Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    'no': { birre: '🍺 Øl & Grunnaperitiff', spritz: '🥂 Spritz & Klassiske Cocktailer — €6,00', premium: '⭐ Premium Cocktailer — €8,00' },
    'fi': { birre: '🍺 Oluet & Perusaperitiivit', spritz: '🥂 Spritz & Klassiset Cocktailit — €6,00', premium: '⭐ Premium-Cocktailit — €8,00' },
    'el': { birre: '🍺 Μπύρες & Βασικά Απεριτίφ', spritz: '🥂 Spritz & Κλασικά Κοκτέιλ — €6,00', premium: '⭐ Premium Κοκτέιλ — €8,00' },
    'cs': { birre: '🍺 Piva & Základní Aperitivy', spritz: '🥂 Spritz & Klasické Koktejly — €6,00', premium: '⭐ Prémiové Koktejly — €8,00' },
    'hu': { birre: '🍺 Sörök & Alap Aperitifek', spritz: '🥂 Spritz & Klasszikus Koktélok — €6,00', premium: '⭐ Prémium Koktélok — €8,00' },
    'bg': { birre: '🍺 Бири & Основни Аперитиви', spritz: '🥂 Спритц & Класически Коктейли — €6,00', premium: '⭐ Премиум Коктейли — €8,00' },
    'sk': { birre: '🍺 Pivá & Základné Aperitívy', spritz: '🥂 Spritz & Klasické Koktaily — €6,00', premium: '⭐ Prémiové Koktaily — €8,00' },
    'hr': { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    'sr': { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spric & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    'sl': { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    'tr': { birre: '🍺 Biralar & Temel Aperitifler', spritz: '🥂 Spritz & Klasik Kokteyller — €6,00', premium: '⭐ Premium Kokteyller — €8,00' },
    'ar': { birre: '🍺 البيرة والمقبلات الأساسية', spritz: '🥂 سبريتز والكوكتيلات الكلاسيكية — €6.00', premium: '⭐ الكوكتيلات المميزة — €8.00' },
    'zh-CN': { birre: '🍺 啤酒和基础开胃酒', spritz: '🥂 Spritz和经典鸡尾酒 — €6.00', premium: '⭐ 高级鸡尾酒 — €8.00' },
    'ja': { birre: '🍺 ビール & ベースアペリティフ', spritz: '🥂 スプリッツ & クラシックカクテル — €6.00', premium: '⭐ プレミアムカクテル — €8.00' },
    'ko': { birre: '🍺 맥주 & 기본 아페리티프', spritz: '🥂 스프리츠 & 클래식 칵테일 — €6.00', premium: '⭐ 프리미엄 칵테일 — €8.00' },
    'hi': { birre: '🍺 बीयर और बेसिक एपेरिटिफ़', spritz: '🥂 स्प्रिट्ज़ और क्लासिक कॉकटेल — €6.00', premium: '⭐ प्रीमियम कॉकटेल — €8.00' },
    'bn': { birre: '🍺 বিয়ার এবং বেসিক এপেরিটিফ', spritz: '🥂 স্প্রিৎজ এবং ক্লাসিক ককটেল — €৬.০০', premium: '⭐ প্রিমিয়াম ককটেল — €৮.০০' },
    'ur': { birre: '🍺 بیئر اور بنیادی ایپریٹف', spritz: '🥂 اسپرٹز اور کلاسک کاکٹیل — €6.00', premium: '⭐ پریمیم کاکٹیل — €8.00' },
    'fa': { birre: '🍺 آبجو و اپریتیف پایه', spritz: '🥂 اسپریتز و کوکتل‌های کلاسیک — €6.00', premium: '⭐ کوکتل‌های ممتاز — €8.00' },
    'vi': { birre: '🍺 Bia & Khai Vị Cơ Bản', spritz: '🥂 Spritz & Cocktail Cổ Điển — €6.00', premium: '⭐ Cocktail Cao Cấp — €8.00' },
    'th': { birre: '🍺 เบียร์ & อาเปอริทีฟพื้นฐาน', spritz: '🥂 สปริตซ์ & ค็อกเทลคลาสสิก — €6.00', premium: '⭐ ค็อกเทลพรีเมียม — €8.00' }
  };
  if (typeof BAR_GROUP_TITLES !== 'undefined') {
    Object.keys(GROUP_PATCH).forEach(function (lang) {
      Object.keys(GROUP_PATCH[lang]).forEach(function (groupKey) {
        if (!BAR_GROUP_TITLES[groupKey]) BAR_GROUP_TITLES[groupKey] = {};
        BAR_GROUP_TITLES[groupKey][lang] = GROUP_PATCH[lang][groupKey];
      });
    });
    console.log('[bar_trans_patch] Merged ' + Object.keys(GROUP_PATCH).length + ' languages into BAR_GROUP_TITLES.');
  } else {
    console.warn('[bar_trans_patch] BAR_GROUP_TITLES not found — group headers were not patched.');
  }
})();
