/**
 * bar_trans_patch.js
 * ---------------------------------------------------------------
 * Extends BAR_TRANS with all 28 extra languages.
 * Paste this AFTER the existing BAR_TRANS / BAR_ITEMS block.
 * ---------------------------------------------------------------
 */
(function () {
  var PATCH = {
    nl: {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Cafeïnevrije Koffie',
      "Caffè D'Orzo Piccolo": 'Gerstenkoffie Klein',
      "Caffè D'Orzo Grande": 'Gerstenkoffie Groot',
      'Caffè Ginseng Piccolo': 'Ginsengkoffie Klein',
      'Caffè Ginseng Grande': 'Ginsengkoffie Groot',
      'Caffè Corretto': 'Koffie met Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Warme Thee',
      'Infusi': 'Kruidenthee',
      'Cioccolata Calda': 'Warme Chocolade',
      'Acqua Naturale 1 lt': 'Plat Water 1 lt',
      'Acqua Gassata 1 lt': 'Bruisend Water 1 lt',
      'Estathé Limone': 'Ijsthee Citroen',
      'Estathé Pesca': 'Ijsthee Perzik',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citroen',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Perzikensap',
      'Succo di Frutta Ananas': 'Ananassap',
      'Succo di Frutta Arancia': 'Sinaasappelsap',
      'Succo di Frutta Albicocca': 'Abrikozensap',
      'Succo di Frutta ACE': 'ACE-sap',
      'Succo di Frutta Pera': 'Perensap',
      'Birra Bottiglia 33 cl': 'Fles Bier 33 cl',
      'Digestivi': 'Digestieven',
      'Distillati': 'Gedistilleerde Dranken',
      'Shot Alcolici': 'Alcoholshots',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citroen'
    },
    es: {
      'Caffè Espresso': 'Café Espresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      "Caffè D'Orzo Piccolo": 'Café de Cebada Pequeño',
      "Caffè D'Orzo Grande": 'Café de Cebada Grande',
      'Caffè Ginseng Piccolo': 'Café de Ginseng Pequeño',
      'Caffè Ginseng Grande': 'Café de Ginseng Grande',
      'Caffè Corretto': 'Café con Grappa',
      'Caffè Latte': 'Café con Leche',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Té Caliente',
      'Infusi': 'Infusiones',
      'Cioccolata Calda': 'Chocolate Caliente',
      'Acqua Naturale 1 lt': 'Agua Sin Gas 1 lt',
      'Acqua Gassata 1 lt': 'Agua Con Gas 1 lt',
      'Estathé Limone': 'Té Frío Limón',
      'Estathé Pesca': 'Té Frío Melocotón',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Zumo de Melocotón',
      'Succo di Frutta Ananas': 'Zumo de Piña',
      'Succo di Frutta Arancia': 'Zumo de Naranja',
      'Succo di Frutta Albicocca': 'Zumo de Albaricoque',
      'Succo di Frutta ACE': 'Zumo ACE',
      'Succo di Frutta Pera': 'Zumo de Pera',
      'Birra Bottiglia 33 cl': 'Cerveza Botella 33 cl',
      'Digestivi': 'Digestivos',
      'Distillati': 'Destilados',
      'Shot Alcolici': 'Chupitos',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Ron & Cola',
      'Gin Tonic': 'Gin Tónic',
      'Gin Lemon': 'Gin Limón'
    },
    pt: {
      'Caffè Espresso': 'Café Expresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      "Caffè D'Orzo Piccolo": 'Café de Cevada Pequeno',
      "Caffè D'Orzo Grande": 'Café de Cevada Grande',
      'Caffè Ginseng Piccolo': 'Café de Ginseng Pequeno',
      'Caffè Ginseng Grande': 'Café de Ginseng Grande',
      'Caffè Corretto': 'Café com Grappa',
      'Caffè Latte': 'Café com Leite',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Chá Quente',
      'Infusi': 'Infusões',
      'Cioccolata Calda': 'Chocolate Quente',
      'Acqua Naturale 1 lt': 'Água Sem Gás 1 lt',
      'Acqua Gassata 1 lt': 'Água Com Gás 1 lt',
      'Estathé Limone': 'Chá Frio Limão',
      'Estathé Pesca': 'Chá Frio Pêssego',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limão',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Sumo de Pêssego',
      'Succo di Frutta Ananas': 'Sumo de Ananás',
      'Succo di Frutta Arancia': 'Sumo de Laranja',
      'Succo di Frutta Albicocca': 'Sumo de Alperce',
      'Succo di Frutta ACE': 'Sumo ACE',
      'Succo di Frutta Pera': 'Sumo de Pera',
      'Birra Bottiglia 33 cl': 'Cerveja Garrafa 33 cl',
      'Digestivi': 'Digestivos',
      'Distillati': 'Destilados',
      'Shot Alcolici': 'Shots',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tónico',
      'Gin Lemon': 'Gin Limão'
    },
    ru: {
      'Caffè Espresso': 'Кофе Эспрессо',
      'Caffè Decaffeinato': 'Кофе без Кофеина',
      "Caffè D'Orzo Piccolo": 'Ячменный Кофе Маленький',
      "Caffè D'Orzo Grande": 'Ячменный Кофе Большой',
      'Caffè Ginseng Piccolo': 'Женьшеневый Кофе Маленький',
      'Caffè Ginseng Grande': 'Женьшеневый Кофе Большой',
      'Caffè Corretto': 'Кофе с Граппой',
      'Caffè Latte': 'Кофе Латте',
      'Latte Macchiato': 'Латте Макиато',
      'Thè Caldo': 'Горячий Чай',
      'Infusi': 'Травяной Чай',
      'Cioccolata Calda': 'Горячий Шоколад',
      'Acqua Naturale 1 lt': 'Негазированная Вода 1 л',
      'Acqua Gassata 1 lt': 'Газированная Вода 1 л',
      'Estathé Limone': 'Холодный Чай Лимон',
      'Estathé Pesca': 'Холодный Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Персиковый Сок',
      'Succo di Frutta Ananas': 'Ананасовый Сок',
      'Succo di Frutta Arancia': 'Апельсиновый Сок',
      'Succo di Frutta Albicocca': 'Абрикосовый Сок',
      'Succo di Frutta ACE': 'Сок ACE',
      'Succo di Frutta Pera': 'Грушевый Сок',
      'Birra Bottiglia 33 cl': 'Пиво в Бутылке 33 кл',
      'Digestivi': 'Дижестивы',
      'Distillati': 'Дистилляты',
      'Shot Alcolici': 'Алкогольные Шоты',
      'Whisky & Coca': 'Виски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тоник',
      'Gin Lemon': 'Джин & Лимон'
    },
    pl: {
      'Caffè Espresso': 'Kawa Espresso',
      'Caffè Decaffeinato': 'Kawa Bezkofeinowa',
      "Caffè D'Orzo Piccolo": 'Kawa Jęczmienna Mała',
      "Caffè D'Orzo Grande": 'Kawa Jęczmienna Duża',
      'Caffè Ginseng Piccolo': 'Kawa Żeńszeniowa Mała',
      'Caffè Ginseng Grande': 'Kawa Żeńszeniowa Duża',
      'Caffè Corretto': 'Kawa z Grappą',
      'Caffè Latte': 'Kawa Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Gorąca Herbata',
      'Infusi': 'Herbaty Ziołowe',
      'Cioccolata Calda': 'Gorąca Czekolada',
      'Acqua Naturale 1 lt': 'Woda Niegazowana 1 lt',
      'Acqua Gassata 1 lt': 'Woda Gazowana 1 lt',
      'Estathé Limone': 'Mrożona Herbata Cytrynowa',
      'Estathé Pesca': 'Mrożona Herbata Brzoskwiniowa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Cytryna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Sok Brzoskwiniowy',
      'Succo di Frutta Ananas': 'Sok Ananasowy',
      'Succo di Frutta Arancia': 'Sok Pomarańczowy',
      'Succo di Frutta Albicocca': 'Sok Morelowy',
      'Succo di Frutta ACE': 'Sok ACE',
      'Succo di Frutta Pera': 'Sok Gruszkowy',
      'Birra Bottiglia 33 cl': 'Piwo Butelkowe 33 cl',
      'Digestivi': 'Digestify',
      'Distillati': 'Destylaty',
      'Shot Alcolici': 'Shoty Alkoholowe',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Cytryna'
    },
    uk: {
      'Caffè Espresso': 'Кава Еспресо',
      'Caffè Decaffeinato': 'Кава без Кофеїну',
      "Caffè D'Orzo Piccolo": 'Ячмінна Кава Мала',
      "Caffè D'Orzo Grande": 'Ячмінна Кава Велика',
      'Caffè Ginseng Piccolo': 'Женьшенева Кава Мала',
      'Caffè Ginseng Grande': 'Женьшенева Кава Велика',
      'Caffè Corretto': 'Кава з Граппою',
      'Caffè Latte': 'Кава Латте',
      'Latte Macchiato': 'Латте Макіато',
      'Thè Caldo': 'Гарячий Чай',
      'Infusi': 'Трав\'яний Чай',
      'Cioccolata Calda': 'Гарячий Шоколад',
      'Acqua Naturale 1 lt': 'Негазована Вода 1 л',
      'Acqua Gassata 1 lt': 'Газована Вода 1 л',
      'Estathé Limone': 'Холодний Чай Лимон',
      'Estathé Pesca': 'Холодний Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Персиковий Сік',
      'Succo di Frutta Ananas': 'Ананасовий Сік',
      'Succo di Frutta Arancia': 'Апельсиновий Сік',
      'Succo di Frutta Albicocca': 'Абрикосовий Сік',
      'Succo di Frutta ACE': 'Сік ACE',
      'Succo di Frutta Pera': 'Грушевий Сік',
      'Birra Bottiglia 33 cl': 'Пиво в Пляшці 33 кл',
      'Digestivi': 'Дижестиви',
      'Distillati': 'Дистиляти',
      'Shot Alcolici': 'Алкогольні Шоти',
      'Whisky & Coca': 'Віскі & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тонік',
      'Gin Lemon': 'Джин & Лимон'
    },
    ro: {
      'Caffè Espresso': 'Cafea Espresso',
      'Caffè Decaffeinato': 'Cafea Decofeinizată',
      "Caffè D'Orzo Piccolo": 'Cafea de Orz Mică',
      "Caffè D'Orzo Grande": 'Cafea de Orz Mare',
      'Caffè Ginseng Piccolo': 'Cafea de Ginseng Mică',
      'Caffè Ginseng Grande': 'Cafea de Ginseng Mare',
      'Caffè Corretto': 'Cafea cu Grappa',
      'Caffè Latte': 'Cafea Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Ceai Cald',
      'Infusi': 'Infuzii',
      'Cioccolata Calda': 'Ciocolată Caldă',
      'Acqua Naturale 1 lt': 'Apă Plată 1 lt',
      'Acqua Gassata 1 lt': 'Apă Carbogazoasă 1 lt',
      'Estathé Limone': 'Ceai Rece Lămâie',
      'Estathé Pesca': 'Ceai Rece Piersică',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Lămâie',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Suc de Piersică',
      'Succo di Frutta Ananas': 'Suc de Ananas',
      'Succo di Frutta Arancia': 'Suc de Portocale',
      'Succo di Frutta Albicocca': 'Suc de Caise',
      'Succo di Frutta ACE': 'Suc ACE',
      'Succo di Frutta Pera': 'Suc de Pere',
      'Birra Bottiglia 33 cl': 'Bere Sticlă 33 cl',
      'Digestivi': 'Digestive',
      'Distillati': 'Distilate',
      'Shot Alcolici': 'Shoturi Alcoolice',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin Tonic',
      'Gin Lemon': 'Gin Lămâie'
    },
    sv: {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfritt Kaffe',
      "Caffè D'Orzo Piccolo": 'Korngkaffe Litet',
      "Caffè D'Orzo Grande": 'Kornkaffe Stort',
      'Caffè Ginseng Piccolo': 'Ginsengkaffe Litet',
      'Caffè Ginseng Grande': 'Ginsengkaffe Stort',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varmt Te',
      'Infusi': 'Örtte',
      'Cioccolata Calda': 'Varm Choklad',
      'Acqua Naturale 1 lt': 'Stilla Vatten 1 lt',
      'Acqua Gassata 1 lt': 'Kolsyrat Vatten 1 lt',
      'Estathé Limone': 'Iste Citron',
      'Estathé Pesca': 'Iste Persika',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Persikajuice',
      'Succo di Frutta Ananas': 'Ananajuice',
      'Succo di Frutta Arancia': 'Apelsinjuice',
      'Succo di Frutta Albicocca': 'Aprikosjuice',
      'Succo di Frutta ACE': 'ACE-juice',
      'Succo di Frutta Pera': 'Päronjuice',
      'Birra Bottiglia 33 cl': 'Flasköl 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillat',
      'Shot Alcolici': 'Alkoholshots',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    da: {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      "Caffè D'Orzo Piccolo": 'Bygkaffe Lille',
      "Caffè D'Orzo Grande": 'Bygkaffe Stor',
      'Caffè Ginseng Piccolo': 'Ginsengkaffe Lille',
      'Caffè Ginseng Grande': 'Ginsengkaffe Stor',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varm Te',
      'Infusi': 'Urtethe',
      'Cioccolata Calda': 'Varm Chokolade',
      'Acqua Naturale 1 lt': 'Stille Vand 1 lt',
      'Acqua Gassata 1 lt': 'Kulsyreholdigt Vand 1 lt',
      'Estathé Limone': 'Isite Citron',
      'Estathé Pesca': 'Isite Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Ferskenjuice',
      'Succo di Frutta Ananas': 'Ananajuice',
      'Succo di Frutta Arancia': 'Appelsinjuice',
      'Succo di Frutta Albicocca': 'Abrikosejuice',
      'Succo di Frutta ACE': 'ACE-juice',
      'Succo di Frutta Pera': 'Pærejuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillater',
      'Shot Alcolici': 'Alkoholshots',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    no: {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      "Caffè D'Orzo Piccolo": 'Byggkaffe Liten',
      "Caffè D'Orzo Grande": 'Byggkaffe Stor',
      'Caffè Ginseng Piccolo': 'Ginsengkaffe Liten',
      'Caffè Ginseng Grande': 'Ginsengkaffe Stor',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Varm Te',
      'Infusi': 'Urtete',
      'Cioccolata Calda': 'Varm Sjokolade',
      'Acqua Naturale 1 lt': 'Stille Vann 1 lt',
      'Acqua Gassata 1 lt': 'Kullsyreholdig Vann 1 lt',
      'Estathé Limone': 'Iste Sitron',
      'Estathé Pesca': 'Iste Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Ferskensjuice',
      'Succo di Frutta Ananas': 'Ananassjuice',
      'Succo di Frutta Arancia': 'Appelsinjuice',
      'Succo di Frutta Albicocca': 'Aprikos juice',
      'Succo di Frutta ACE': 'ACE-juice',
      'Succo di Frutta Pera': 'Pærejuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Digestivi': 'Digestif',
      'Distillati': 'Destillater',
      'Shot Alcolici': 'Alkoholshots',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitron'
    },
    fi: {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Kofeiiniton Kahvi',
      "Caffè D'Orzo Piccolo": 'Ohrakahvi Pieni',
      "Caffè D'Orzo Grande": 'Ohrakahvi Suuri',
      'Caffè Ginseng Piccolo': 'Ginsengkahvi Pieni',
      'Caffè Ginseng Grande': 'Ginsengkahvi Suuri',
      'Caffè Corretto': 'Kahvi Grappalla',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Kuuma Tee',
      'Infusi': 'Yrttitee',
      'Cioccolata Calda': 'Kuuma Kaakao',
      'Acqua Naturale 1 lt': 'Hanavesi 1 lt',
      'Acqua Gassata 1 lt': 'Kivennäisvesi 1 lt',
      'Estathé Limone': 'Jäätee Sitruuna',
      'Estathé Pesca': 'Jäätee Persikka',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitruuna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Persikkamehu',
      'Succo di Frutta Ananas': 'Anananasmehu',
      'Succo di Frutta Arancia': 'Appelsiinimehu',
      'Succo di Frutta Albicocca': 'Aprikoosimehu',
      'Succo di Frutta ACE': 'ACE-mehu',
      'Succo di Frutta Pera': 'Päärynämehu',
      'Birra Bottiglia 33 cl': 'Olutpullo 33 cl',
      'Digestivi': 'Digestiivit',
      'Distillati': 'Väkevät Alkoholit',
      'Shot Alcolici': 'Alkoholishotteja',
      'Whisky & Coca': 'Viski & Cola',
      'Rhum & Coca': 'Rommi & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitruuna'
    },
    el: {
      'Caffè Espresso': 'Καφές Εσπρέσο',
      'Caffè Decaffeinato': 'Καφές Ντεκαφεϊνέ',
      "Caffè D'Orzo Piccolo": 'Καφές Κριθαριού Μικρός',
      "Caffè D'Orzo Grande": 'Καφές Κριθαριού Μεγάλος',
      'Caffè Ginseng Piccolo': 'Καφές Τζίνσενγκ Μικρός',
      'Caffè Ginseng Grande': 'Καφές Τζίνσενγκ Μεγάλος',
      'Caffè Corretto': 'Καφές με Γκράπα',
      'Caffè Latte': 'Καφές Λάτε',
      'Latte Macchiato': 'Λάτε Μακιάτο',
      'Thè Caldo': 'Ζεστό Τσάι',
      'Infusi': 'Αφεψήματα',
      'Cioccolata Calda': 'Ζεστή Σοκολάτα',
      'Acqua Naturale 1 lt': 'Φυσικό Νερό 1 lt',
      'Acqua Gassata 1 lt': 'Ανθρακούχο Νερό 1 lt',
      'Estathé Limone': 'Παγωμένο Τσάι Λεμόνι',
      'Estathé Pesca': 'Παγωμένο Τσάι Ροδάκινο',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Λεμόνι',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Χυμός Ροδάκινο',
      'Succo di Frutta Ananas': 'Χυμός Ανανά',
      'Succo di Frutta Arancia': 'Χυμός Πορτοκάλι',
      'Succo di Frutta Albicocca': 'Χυμός Βερίκοκο',
      'Succo di Frutta ACE': 'Χυμός ACE',
      'Succo di Frutta Pera': 'Χυμός Αχλάδι',
      'Birra Bottiglia 33 cl': 'Μπύρα Μπουκάλι 33 cl',
      'Digestivi': 'Πεπτικά',
      'Distillati': 'Αποστάγματα',
      'Shot Alcolici': 'Σφηνάκια',
      'Whisky & Coca': 'Ουίσκι & Κόλα',
      'Rhum & Coca': 'Ρούμι & Κόλα',
      'Gin Tonic': 'Τζιν Τόνικ',
      'Gin Lemon': 'Τζιν Λεμόνι'
    },
    cs: {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      "Caffè D'Orzo Piccolo": 'Ječmenná Káva Malá',
      "Caffè D'Orzo Grande": 'Ječmenná Káva Velká',
      'Caffè Ginseng Piccolo': 'Ženšenová Káva Malá',
      'Caffè Ginseng Grande': 'Ženšenová Káva Velká',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Horký Čaj',
      'Infusi': 'Bylinné Čaje',
      'Cioccolata Calda': 'Horká Čokoláda',
      'Acqua Naturale 1 lt': 'Neperlivá Voda 1 lt',
      'Acqua Gassata 1 lt': 'Perlivá Voda 1 lt',
      'Estathé Limone': 'Ledový Čaj Citron',
      'Estathé Pesca': 'Ledový Čaj Broskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Broskvový Džus',
      'Succo di Frutta Ananas': 'Ananasový Džus',
      'Succo di Frutta Arancia': 'Pomerančový Džus',
      'Succo di Frutta Albicocca': 'Meruňkový Džus',
      'Succo di Frutta ACE': 'ACE Džus',
      'Succo di Frutta Pera': 'Hruškovový Džus',
      'Birra Bottiglia 33 cl': 'Pivo v Láhvi 33 cl',
      'Digestivi': 'Digestivy',
      'Distillati': 'Destiláty',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citron'
    },
    hu: {
      'Caffè Espresso': 'Eszpresszó',
      'Caffè Decaffeinato': 'Koffeinmentes Kávé',
      "Caffè D'Orzo Piccolo": 'Árpakávé Kis',
      "Caffè D'Orzo Grande": 'Árpakávé Nagy',
      'Caffè Ginseng Piccolo': 'Ginszeng Kávé Kis',
      'Caffè Ginseng Grande': 'Ginszeng Kávé Nagy',
      'Caffè Corretto': 'Kávé Grappával',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Meleg Tea',
      'Infusi': 'Gyógynövény Tea',
      'Cioccolata Calda': 'Forró Csokoládé',
      'Acqua Naturale 1 lt': 'Szénsavmentes Víz 1 lt',
      'Acqua Gassata 1 lt': 'Szénsavas Víz 1 lt',
      'Estathé Limone': 'Jeges Tea Citrom',
      'Estathé Pesca': 'Jeges Tea Barack',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrom',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Barackjuice',
      'Succo di Frutta Ananas': 'Ananászjuice',
      'Succo di Frutta Arancia': 'Narancsjuice',
      'Succo di Frutta Albicocca': 'Kajszijuice',
      'Succo di Frutta ACE': 'ACE Juice',
      'Succo di Frutta Pera': 'Körte juice',
      'Birra Bottiglia 33 cl': 'Üveges Sör 33 cl',
      'Digestivi': 'Digestifek',
      'Distillati': 'Desztillátumok',
      'Shot Alcolici': 'Alkoholos Shotok',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrom'
    },
    bg: {
      'Caffè Espresso': 'Кафе Еспресо',
      'Caffè Decaffeinato': 'Безкофеиново Кафе',
      "Caffè D'Orzo Piccolo": 'Ечемично Кафе Малко',
      "Caffè D'Orzo Grande": 'Ечемично Кафе Голямо',
      'Caffè Ginseng Piccolo': 'Женшеново Кафе Малко',
      'Caffè Ginseng Grande': 'Женшеново Кафе Голямо',
      'Caffè Corretto': 'Кафе с Грапа',
      'Caffè Latte': 'Кафе Лате',
      'Latte Macchiato': 'Лате Макиато',
      'Thè Caldo': 'Горещ Чай',
      'Infusi': 'Билков Чай',
      'Cioccolata Calda': 'Горещ Шоколад',
      'Acqua Naturale 1 lt': 'Негазирана Вода 1 л',
      'Acqua Gassata 1 lt': 'Газирана Вода 1 л',
      'Estathé Limone': 'Студен Чай Лимон',
      'Estathé Pesca': 'Студен Чай Праскова',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Прасковен Сок',
      'Succo di Frutta Ananas': 'Ананасов Сок',
      'Succo di Frutta Arancia': 'Портокалов Сок',
      'Succo di Frutta Albicocca': 'Кайсиев Сок',
      'Succo di Frutta ACE': 'Сок ACE',
      'Succo di Frutta Pera': 'Крушов Сок',
      'Birra Bottiglia 33 cl': 'Бутилирана Бира 33 кл',
      'Digestivi': 'Дижестиви',
      'Distillati': 'Дестилати',
      'Shot Alcolici': 'Алкохолни Шотове',
      'Whisky & Coca': 'Уиски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин Тоник',
      'Gin Lemon': 'Джин Лимон'
    },
    sk: {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      "Caffè D'Orzo Piccolo": 'Jačmenná Káva Malá',
      "Caffè D'Orzo Grande": 'Jačmenná Káva Veľká',
      'Caffè Ginseng Piccolo': 'Ženšenová Káva Malá',
      'Caffè Ginseng Grande': 'Ženšenová Káva Veľká',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Horúci Čaj',
      'Infusi': 'Bylinkové Čaje',
      'Cioccolata Calda': 'Horúca Čokoláda',
      'Acqua Naturale 1 lt': 'Neperlivá Voda 1 lt',
      'Acqua Gassata 1 lt': 'Perlivá Voda 1 lt',
      'Estathé Limone': 'Ľadový Čaj Citrón',
      'Estathé Pesca': 'Ľadový Čaj Broskyňa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Broskyňový Džús',
      'Succo di Frutta Ananas': 'Ananásový Džús',
      'Succo di Frutta Arancia': 'Pomarančový Džús',
      'Succo di Frutta Albicocca': 'Marhuľový Džús',
      'Succo di Frutta ACE': 'ACE Džús',
      'Succo di Frutta Pera': 'Hrušový Džús',
      'Birra Bottiglia 33 cl': 'Fľaška Piva 33 cl',
      'Digestivi': 'Digestívy',
      'Distillati': 'Destiláty',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrón'
    },
    hr: {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Kava bez Kofeina',
      "Caffè D'Orzo Piccolo": 'Ječmena Kava Mala',
      "Caffè D'Orzo Grande": 'Ječmena Kava Velika',
      'Caffè Ginseng Piccolo': 'Ginzeng Kava Mala',
      'Caffè Ginseng Grande': 'Ginzeng Kava Velika',
      'Caffè Corretto': 'Kava s Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Sok od Breskve',
      'Succo di Frutta Ananas': 'Sok od Ananasa',
      'Succo di Frutta Arancia': 'Sok od Naranče',
      'Succo di Frutta Albicocca': 'Sok od Marelice',
      'Succo di Frutta ACE': 'ACE Sok',
      'Succo di Frutta Pera': 'Sok od Kruške',
      'Birra Bottiglia 33 cl': 'Pivo Boca 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Shotovi',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limun'
    },
    sr: {
      'Caffè Espresso': 'Kafa Espreso',
      'Caffè Decaffeinato': 'Kafa bez Kofeina',
      "Caffè D'Orzo Piccolo": 'Ječmena Kafa Mala',
      "Caffè D'Orzo Grande": 'Ječmena Kafa Velika',
      'Caffè Ginseng Piccolo': 'Ginzeng Kafa Mala',
      'Caffè Ginseng Grande': 'Ginzeng Kafa Velika',
      'Caffè Corretto': 'Kafa sa Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Sok od Breskve',
      'Succo di Frutta Ananas': 'Sok od Ananasa',
      'Succo di Frutta Arancia': 'Sok od Pomorandže',
      'Succo di Frutta Albicocca': 'Sok od Kajsije',
      'Succo di Frutta ACE': 'ACE Sok',
      'Succo di Frutta Pera': 'Sok od Kruške',
      'Birra Bottiglia 33 cl': 'Pivo Flaša 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Šotovi',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rum & Kola',
      'Gin Tonic': 'Džin Tonik',
      'Gin Lemon': 'Džin Limun'
    },
    sl: {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Brezkofeinska Kava',
      "Caffè D'Orzo Piccolo": 'Ječmenova Kava Mala',
      "Caffè D'Orzo Grande": 'Ječmenova Kava Velika',
      'Caffè Ginseng Piccolo': 'Ginsenova Kava Mala',
      'Caffè Ginseng Grande': 'Ginsenova Kava Velika',
      'Caffè Corretto': 'Kava z Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Topel Čaj',
      'Infusi': 'Zeliščni Čaj',
      'Cioccolata Calda': 'Vroča Čokolada',
      'Acqua Naturale 1 lt': 'Negazirana Voda 1 lt',
      'Acqua Gassata 1 lt': 'Gazirana Voda 1 lt',
      'Estathé Limone': 'Ledeni Čaj Limona',
      'Estathé Pesca': 'Ledeni Čaj Breskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limona',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Breskov Sok',
      'Succo di Frutta Ananas': 'Ananasov Sok',
      'Succo di Frutta Arancia': 'Pomarančev Sok',
      'Succo di Frutta Albicocca': 'Marelin Sok',
      'Succo di Frutta ACE': 'ACE Sok',
      'Succo di Frutta Pera': 'Hruskov Sok',
      'Birra Bottiglia 33 cl': 'Stekleničeno Pivo 33 cl',
      'Digestivi': 'Digestivi',
      'Distillati': 'Destilati',
      'Shot Alcolici': 'Alkoholni Shoti',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limona'
    },
    tr: {
      'Caffè Espresso': 'Espresso Kahve',
      'Caffè Decaffeinato': 'Kafeinsiz Kahve',
      "Caffè D'Orzo Piccolo": 'Arpa Kahvesi Küçük',
      "Caffè D'Orzo Grande": 'Arpa Kahvesi Büyük',
      'Caffè Ginseng Piccolo': 'Ginseng Kahvesi Küçük',
      'Caffè Ginseng Grande': 'Ginseng Kahvesi Büyük',
      'Caffè Corretto': 'Grappa\'lı Kahve',
      'Caffè Latte': 'Sütlü Kahve',
      'Latte Macchiato': 'Latte Macchiato',
      'Thè Caldo': 'Sıcak Çay',
      'Infusi': 'Bitki Çayı',
      'Cioccolata Calda': 'Sıcak Çikolata',
      'Acqua Naturale 1 lt': 'Doğal Su 1 lt',
      'Acqua Gassata 1 lt': 'Gazlı Su 1 lt',
      'Estathé Limone': 'Soğuk Çay Limon',
      'Estathé Pesca': 'Soğuk Çay Şeftali',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limon',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta Pesca': 'Şeftali Suyu',
      'Succo di Frutta Ananas': 'Ananas Suyu',
      'Succo di Frutta Arancia': 'Portakal Suyu',
      'Succo di Frutta Albicocca': 'Kayısı Suyu',
      'Succo di Frutta ACE': 'ACE Meyve Suyu',
      'Succo di Frutta Pera': 'Armut Suyu',
      'Birra Bottiglia 33 cl': 'Şişe Bira 33 cl',
      'Digestivi': 'Digestifler',
      'Distillati': 'Damıtılmış İçkiler',
      'Shot Alcolici': 'Alkol Şotları',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rom & Kola',
      'Gin Tonic': 'Cin Tonik',
      'Gin Lemon': 'Cin Limon'
    },
    ar: {
      'Caffè Espresso': 'قهوة إسبريسو',
      'Caffè Decaffeinato': 'قهوة منزوعة الكافيين',
      "Caffè D'Orzo Piccolo": 'قهوة الشعير صغيرة',
      "Caffè D'Orzo Grande": 'قهوة الشعير كبيرة',
      'Caffè Ginseng Piccolo': 'قهوة الجنسنغ صغيرة',
      'Caffè Ginseng Grande': 'قهوة الجنسنغ كبيرة',
      'Caffè Corretto': 'قهوة بالغراپا',
      'Caffè Latte': 'كافيه لاتيه',
      'Latte Macchiato': 'لاتيه ماكياتو',
      'Thè Caldo': 'شاي ساخن',
      'Infusi': 'شاي أعشاب',
      'Cioccolata Calda': 'شوكولاتة ساخنة',
      'Acqua Naturale 1 lt': 'مياه طبيعية 1 لتر',
      'Acqua Gassata 1 lt': 'مياه غازية 1 لتر',
      'Estathé Limone': 'شاي بارد بالليمون',
      'Estathé Pesca': 'شاي بارد بالخوخ',
      'Schweppes': 'شويبس',
      'Schweppes Lemon': 'شويبس ليمون',
      'Crodino': 'كرودينو',
      'Sanbitter': 'سانبيتر',
      'Succo di Frutta Pesca': 'عصير الخوخ',
      'Succo di Frutta Ananas': 'عصير الأناناس',
      'Succo di Frutta Arancia': 'عصير البرتقال',
      'Succo di Frutta Albicocca': 'عصير المشمش',
      'Succo di Frutta ACE': 'عصير ACE',
      'Succo di Frutta Pera': 'عصير الكمثرى',
      'Birra Bottiglia 33 cl': 'بيرة زجاجة 33 سل',
      'Digestivi': 'مشروبات هضمية',
      'Distillati': 'مقطرات',
      'Shot Alcolici': 'شوتات كحولية',
      'Whisky & Coca': 'ويسكي & كولا',
      'Rhum & Coca': 'روم & كولا',
      'Gin Tonic': 'جن & توник',
      'Gin Lemon': 'جن & ليمون'
    },
    'zh-CN': {
      'Caffè Espresso': '意式浓缩咖啡',
      'Caffè Decaffeinato': '低咖啡因咖啡',
      "Caffè D'Orzo Piccolo": '大麦咖啡小杯',
      "Caffè D'Orzo Grande": '大麦咖啡大杯',
      'Caffè Ginseng Piccolo': '人参咖啡小杯',
      'Caffè Ginseng Grande': '人参咖啡大杯',
      'Caffè Corretto': '格拉帕咖啡',
      'Caffè Latte': '拿铁咖啡',
      'Latte Macchiato': '玛奇朵',
      'Thè Caldo': '热茶',
      'Infusi': '花草茶',
      'Cioccolata Calda': '热巧克力',
      'Acqua Naturale 1 lt': '天然矿泉水 1升',
      'Acqua Gassata 1 lt': '气泡水 1升',
      'Estathé Limone': '柠檬冰茶',
      'Estathé Pesca': '桃子冰茶',
      'Schweppes': '施韦普斯',
      'Schweppes Lemon': '施韦普斯柠檬',
      'Crodino': '克罗迪诺',
      'Sanbitter': '桑比特',
      'Succo di Frutta Pesca': '桃汁',
      'Succo di Frutta Ananas': '菠萝汁',
      'Succo di Frutta Arancia': '橙汁',
      'Succo di Frutta Albicocca': '杏汁',
      'Succo di Frutta ACE': 'ACE果汁',
      'Succo di Frutta Pera': '梨汁',
      'Birra Bottiglia 33 cl': '瓶装啤酒 33克拉',
      'Digestivi': '助消化饮品',
      'Distillati': '蒸馏酒',
      'Shot Alcolici': '烈酒一口杯',
      'Whisky & Coca': '威士忌 & 可乐',
      'Rhum & Coca': '朗姆酒 & 可乐',
      'Gin Tonic': '金汤力',
      'Gin Lemon': '金柠檬'
    },
    ja: {
      'Caffè Espresso': 'エスプレッソ',
      'Caffè Decaffeinato': 'デカフェコーヒー',
      "Caffè D'Orzo Piccolo": '大麦コーヒー スモール',
      "Caffè D'Orzo Grande": '大麦コーヒー ラージ',
      'Caffè Ginseng Piccolo': '高麗人参コーヒー スモール',
      'Caffè Ginseng Grande': '高麗人参コーヒー ラージ',
      'Caffè Corretto': 'グラッパ入りコーヒー',
      'Caffè Latte': 'カフェラテ',
      'Latte Macchiato': 'ラテマキアート',
      'Thè Caldo': 'ホットティー',
      'Infusi': 'ハーブティー',
      'Cioccolata Calda': 'ホットチョコレート',
      'Acqua Naturale 1 lt': 'ミネラルウォーター 1L',
      'Acqua Gassata 1 lt': '炭酸水 1L',
      'Estathé Limone': 'レモンアイスティー',
      'Estathé Pesca': '桃アイスティー',
      'Schweppes': 'シュウェップス',
      'Schweppes Lemon': 'シュウェップス レモン',
      'Crodino': 'クロディーノ',
      'Sanbitter': 'サンビター',
      'Succo di Frutta Pesca': '桃ジュース',
      'Succo di Frutta Ananas': 'パイナップルジュース',
      'Succo di Frutta Arancia': 'オレンジジュース',
      'Succo di Frutta Albicocca': 'アプリコットジュース',
      'Succo di Frutta ACE': 'ACEジュース',
      'Succo di Frutta Pera': '洋梨ジュース',
      'Birra Bottiglia 33 cl': 'ビール瓶 33cl',
      'Digestivi': '食後酒',
      'Distillati': '蒸留酒',
      'Shot Alcolici': 'アルコールショット',
      'Whisky & Coca': 'ウイスキー & コーラ',
      'Rhum & Coca': 'ラム & コーラ',
      'Gin Tonic': 'ジン & トニック',
      'Gin Lemon': 'ジン & レモン'
    },
    ko: {
      'Caffè Espresso': '에스프레소',
      'Caffè Decaffeinato': '디카페인 커피',
      "Caffè D'Orzo Piccolo": '보리 커피 스몰',
      "Caffè D'Orzo Grande": '보리 커피 라지',
      'Caffè Ginseng Piccolo': '인삼 커피 스몰',
      'Caffè Ginseng Grande': '인삼 커피 라지',
      'Caffè Corretto': '그라파 커피',
      'Caffè Latte': '카페 라테',
      'Latte Macchiato': '라테 마키아토',
      'Thè Caldo': '따뜻한 차',
      'Infusi': '허브티',
      'Cioccolata Calda': '핫 초콜릿',
      'Acqua Naturale 1 lt': '생수 1L',
      'Acqua Gassata 1 lt': '탄산수 1L',
      'Estathé Limone': '레몬 아이스티',
      'Estathé Pesca': '복숭아 아이스티',
      'Schweppes': '슈웹스',
      'Schweppes Lemon': '슈웹스 레몬',
      'Crodino': '크로디노',
      'Sanbitter': '산비터',
      'Succo di Frutta Pesca': '복숭아 주스',
      'Succo di Frutta Ananas': '파인애플 주스',
      'Succo di Frutta Arancia': '오렌지 주스',
      'Succo di Frutta Albicocca': '살구 주스',
      'Succo di Frutta ACE': 'ACE 주스',
      'Succo di Frutta Pera': '배 주스',
      'Birra Bottiglia 33 cl': '병 맥주 33cl',
      'Digestivi': '소화 증진 주류',
      'Distillati': '증류주',
      'Shot Alcolici': '알코올 샷',
      'Whisky & Coca': '위스키 & 콜라',
      'Rhum & Coca': '럼 & 콜라',
      'Gin Tonic': '진 토닉',
      'Gin Lemon': '진 레몬'
    },
    hi: {
      'Caffè Espresso': 'एस्प्रेसो कॉफ़ी',
      'Caffè Decaffeinato': 'डिकैफ़ कॉफ़ी',
      "Caffè D'Orzo Piccolo": 'जौ कॉफ़ी छोटी',
      "Caffè D'Orzo Grande": 'जौ कॉफ़ी बड़ी',
      'Caffè Ginseng Piccolo': 'जिनसेंग कॉफ़ी छोटी',
      'Caffè Ginseng Grande': 'जिनसेंग कॉफ़ी बड़ी',
      'Caffè Corretto': 'ग्रापा के साथ कॉफ़ी',
      'Caffè Latte': 'कैफ़े लाते',
      'Latte Macchiato': 'लाते मैकियाटो',
      'Thè Caldo': 'गर्म चाय',
      'Infusi': 'हर्बल चाय',
      'Cioccolata Calda': 'गर्म चॉकलेट',
      'Acqua Naturale 1 lt': 'सादा पानी 1 लीटर',
      'Acqua Gassata 1 lt': 'कार्बोनेटेड पानी 1 लीटर',
      'Estathé Limone': 'आइस्ड टी नींबू',
      'Estathé Pesca': 'आइस्ड टी आड़ू',
      'Schweppes': 'श्वेप्स',
      'Schweppes Lemon': 'श्वेप्स नींबू',
      'Crodino': 'क्रोदिनो',
      'Sanbitter': 'सैनबिटर',
      'Succo di Frutta Pesca': 'आड़ू का जूस',
      'Succo di Frutta Ananas': 'अनानास का जूस',
      'Succo di Frutta Arancia': 'संतरे का जूस',
      'Succo di Frutta Albicocca': 'खुबानी का जूस',
      'Succo di Frutta ACE': 'ACE जूस',
      'Succo di Frutta Pera': 'नाशपाती का जूस',
      'Birra Bottiglia 33 cl': 'बीयर बोतल 33 cl',
      'Digestivi': 'पाचक पेय',
      'Distillati': 'डिस्टिल्ड शराब',
      'Shot Alcolici': 'अल्कोहल शॉट्स',
      'Whisky & Coca': 'व्हिस्की & कोला',
      'Rhum & Coca': 'रम & कोला',
      'Gin Tonic': 'जिन टॉनिक',
      'Gin Lemon': 'जिन नींबू'
    },
    bn: {
      'Caffè Espresso': 'এস্প্রেসো কফি',
      'Caffè Decaffeinato': 'ডিক্যাফ কফি',
      "Caffè D'Orzo Piccolo": 'বার্লি কফি ছোট',
      "Caffè D'Orzo Grande": 'বার্লি কফি বড়',
      'Caffè Ginseng Piccolo': 'জিনসেং কফি ছোট',
      'Caffè Ginseng Grande': 'জিনসেং কফি বড়',
      'Caffè Corretto': 'গ্রাপা সহ কফি',
      'Caffè Latte': 'ক্যাফে লাতে',
      'Latte Macchiato': 'লাতে মাকিয়াতো',
      'Thè Caldo': 'গরম চা',
      'Infusi': 'হার্বাল চা',
      'Cioccolata Calda': 'গরম চকোলেট',
      'Acqua Naturale 1 lt': 'সাদা পানি ১ লিটার',
      'Acqua Gassata 1 lt': 'কার্বনেটেড পানি ১ লিটার',
      'Estathé Limone': 'আইসড টি লেবু',
      'Estathé Pesca': 'আইসড টি পিচ',
      'Schweppes': 'শোয়েপস',
      'Schweppes Lemon': 'শোয়েপস লেবু',
      'Crodino': 'ক্রোদিনো',
      'Sanbitter': 'স্যানবিটার',
      'Succo di Frutta Pesca': 'পিচ জুস',
      'Succo di Frutta Ananas': 'আনারস জুস',
      'Succo di Frutta Arancia': 'কমলার জুস',
      'Succo di Frutta Albicocca': 'এপ্রিকট জুস',
      'Succo di Frutta ACE': 'ACE জুস',
      'Succo di Frutta Pera': 'নাশপাতি জুস',
      'Birra Bottiglia 33 cl': 'বোতল বিয়ার ৩৩ ক্লি',
      'Digestivi': 'পাচক পানীয়',
      'Distillati': 'পাতিত মদ',
      'Shot Alcolici': 'অ্যালকোহল শট',
      'Whisky & Coca': 'হুইস্কি & কোলা',
      'Rhum & Coca': 'রাম & কোলা',
      'Gin Tonic': 'জিন টনিক',
      'Gin Lemon': 'জিন লেবু'
    },
    ur: {
      'Caffè Espresso': 'ایسپریسو کافی',
      'Caffè Decaffeinato': 'بغیر کیفین کافی',
      "Caffè D'Orzo Piccolo": 'جَو کافی چھوٹی',
      "Caffè D'Orzo Grande": 'جَو کافی بڑی',
      'Caffè Ginseng Piccolo': 'جنسنگ کافی چھوٹی',
      'Caffè Ginseng Grande': 'جنسنگ کافی بڑی',
      'Caffè Corretto': 'گراپا کے ساتھ کافی',
      'Caffè Latte': 'کیفے لاتے',
      'Latte Macchiato': 'لاتے ماکیاتو',
      'Thè Caldo': 'گرم چائے',
      'Infusi': 'جڑی بوٹی چائے',
      'Cioccolata Calda': 'گرم چاکلیٹ',
      'Acqua Naturale 1 lt': 'سادہ پانی ۱ لیٹر',
      'Acqua Gassata 1 lt': 'کاربونیٹڈ پانی ۱ لیٹر',
      'Estathé Limone': 'آئسڈ ٹی لیموں',
      'Estathé Pesca': 'آئسڈ ٹی آڑو',
      'Schweppes': 'شوئپس',
      'Schweppes Lemon': 'شوئپس لیموں',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان بیٹر',
      'Succo di Frutta Pesca': 'آڑو کا جوس',
      'Succo di Frutta Ananas': 'انناس کا جوس',
      'Succo di Frutta Arancia': 'مالٹے کا جوس',
      'Succo di Frutta Albicocca': 'خوبانی کا جوس',
      'Succo di Frutta ACE': 'ACE جوس',
      'Succo di Frutta Pera': 'ناشپاتی کا جوس',
      'Birra Bottiglia 33 cl': 'بوتل بیئر ۳۳ کل',
      'Digestivi': 'ہاضمہ مشروبات',
      'Distillati': 'ڈسٹل شراب',
      'Shot Alcolici': 'الکوہل شاٹ',
      'Whisky & Coca': 'وسکی & کولا',
      'Rhum & Coca': 'رم & کولا',
      'Gin Tonic': 'جن ٹانک',
      'Gin Lemon': 'جن لیموں'
    },
    fa: {
      'Caffè Espresso': 'اسپرسو',
      'Caffè Decaffeinato': 'قهوه بدون کافئین',
      "Caffè D'Orzo Piccolo": 'قهوه جو کوچک',
      "Caffè D'Orzo Grande": 'قهوه جو بزرگ',
      'Caffè Ginseng Piccolo': 'قهوه جینسنگ کوچک',
      'Caffè Ginseng Grande': 'قهوه جینسنگ بزرگ',
      'Caffè Corretto': 'قهوه با گراپا',
      'Caffè Latte': 'کافه لاته',
      'Latte Macchiato': 'لاته ماکیاتو',
      'Thè Caldo': 'چای گرم',
      'Infusi': 'دمنوش گیاهی',
      'Cioccolata Calda': 'شکلات داغ',
      'Acqua Naturale 1 lt': 'آب معدنی ۱ لیتر',
      'Acqua Gassata 1 lt': 'آب گازدار ۱ لیتر',
      'Estathé Limone': 'چای سرد لیمو',
      'Estathé Pesca': 'چای سرد هلو',
      'Schweppes': 'شوپس',
      'Schweppes Lemon': 'شوپس لیمو',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان‌بیتر',
      'Succo di Frutta Pesca': 'آب هلو',
      'Succo di Frutta Ananas': 'آب آناناس',
      'Succo di Frutta Arancia': 'آب پرتقال',
      'Succo di Frutta Albicocca': 'آب زردآلو',
      'Succo di Frutta ACE': 'آب ACE',
      'Succo di Frutta Pera': 'آب گلابی',
      'Birra Bottiglia 33 cl': 'آبجو بطری ۳۳ سی‌سی',
      'Digestivi': 'نوشیدنی گوارشی',
      'Distillati': 'مشروبات تقطیر شده',
      'Shot Alcolici': 'شات الکلی',
      'Whisky & Coca': 'ویسکی & کولا',
      'Rhum & Coca': 'رام & کولا',
      'Gin Tonic': 'جین تونیک',
      'Gin Lemon': 'جین لیمون'
    }
  };

  // Merge into existing BAR_TRANS
  if (typeof BAR_TRANS !== 'undefined') {
    Object.keys(PATCH).forEach(function (lang) {
      if (!BAR_TRANS[lang]) BAR_TRANS[lang] = {};
      Object.assign(BAR_TRANS[lang], PATCH[lang]);
    });
    console.log('[bar_trans_patch] Merged ' + Object.keys(PATCH).length + ' languages into BAR_TRANS.');
  } else {
    console.warn('[bar_trans_patch] BAR_TRANS not found — load this AFTER the BAR_TRANS block.');
  }

  // ------------------------------------------------------------
  // BAR_GROUP_TITLES — same 28 languages for the 3 section headers
  // ------------------------------------------------------------
  var GROUP_PATCH = {
    nl: { birre: '🍺 Bieren & Basisaperitieven', spritz: '🥂 Spritz & Klassieke Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    es: { birre: '🍺 Cervezas & Aperitivos Base', spritz: '🥂 Spritz & Cócteles Clásicos — €6,00', premium: '⭐ Cócteles Premium — €8,00' },
    pt: { birre: '🍺 Cervejas & Aperitivos Base', spritz: '🥂 Spritz & Cocktails Clássicos — €6,00', premium: '⭐ Cocktails Premium — €8,00' },
    ru: { birre: '🍺 Пиво и Базовые Аперитивы', spritz: '🥂 Спритц и Классические Коктейли — €6,00', premium: '⭐ Премиум Коктейли — €8,00' },
    pl: { birre: '🍺 Piwa i Podstawowe Aperitify', spritz: '🥂 Spritz i Klasyczne Koktajle — €6,00', premium: '⭐ Koktajle Premium — €8,00' },
    uk: { birre: '🍺 Пиво та Базові Аперитиви', spritz: '🥂 Спритц і Класичні Коктейлі — €6,00', premium: '⭐ Преміум Коктейлі — €8,00' },
    ro: { birre: '🍺 Beri & Aperitive de Bază', spritz: '🥂 Spritz & Cocktailuri Clasice — €6,00', premium: '⭐ Cocktailuri Premium — €8,00' },
    sv: { birre: '🍺 Öl & Grundaperitif', spritz: '🥂 Spritz & Klassiska Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    da: { birre: '🍺 Øl & Grundaperitif', spritz: '🥂 Spritz & Klassiske Cocktails — €6,00', premium: '⭐ Premium Cocktails — €8,00' },
    no: { birre: '🍺 Øl & Grunnaperitiff', spritz: '🥂 Spritz & Klassiske Cocktailer — €6,00', premium: '⭐ Premium Cocktailer — €8,00' },
    fi: { birre: '🍺 Oluet & Perusaperitiivit', spritz: '🥂 Spritz & Klassiset Cocktailit — €6,00', premium: '⭐ Premium-Cocktailit — €8,00' },
    el: { birre: '🍺 Μπύρες & Βασικά Απεριτίφ', spritz: '🥂 Spritz & Κλασικά Κοκτέιλ — €6,00', premium: '⭐ Premium Κοκτέιλ — €8,00' },
    cs: { birre: '🍺 Piva & Základní Aperitivy', spritz: '🥂 Spritz & Klasické Koktejly — €6,00', premium: '⭐ Prémiové Koktejly — €8,00' },
    hu: { birre: '🍺 Sörök & Alap Aperitifek', spritz: '🥂 Spritz & Klasszikus Koktélok — €6,00', premium: '⭐ Prémium Koktélok — €8,00' },
    bg: { birre: '🍺 Бири & Основни Аперитиви', spritz: '🥂 Спритц & Класически Коктейли — €6,00', premium: '⭐ Премиум Коктейли — €8,00' },
    sk: { birre: '🍺 Pivá & Základné Aperitívy', spritz: '🥂 Spritz & Klasické Koktaily — €6,00', premium: '⭐ Prémiové Koktaily — €8,00' },
    hr: { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    sr: { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spric & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    sl: { birre: '🍺 Piva & Osnovni Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', premium: '⭐ Premium Kokteli — €8,00' },
    tr: { birre: '🍺 Biralar & Temel Aperitifler', spritz: '🥂 Spritz & Klasik Kokteyller — €6,00', premium: '⭐ Premium Kokteyller — €8,00' },
    ar: { birre: '🍺 البيرة والمقبلات الأساسية', spritz: '🥂 سبريتز والكوكتيلات الكلاسيكية — €6.00', premium: '⭐ الكوكتيلات المميزة — €8.00' },
    'zh-CN': { birre: '🍺 啤酒和基础开胃酒', spritz: '🥂 Spritz和经典鸡尾酒 — €6.00', premium: '⭐ 高级鸡尾酒 — €8.00' },
    ja: { birre: '🍺 ビール & ベースアペリティフ', spritz: '🥂 スプリッツ & クラシックカクテル — €6.00', premium: '⭐ プレミアムカクテル — €8.00' },
    ko: { birre: '🍺 맥주 & 기본 아페리티프', spritz: '🥂 스프리츠 & 클래식 칵테일 — €6.00', premium: '⭐ 프리미엄 칵테일 — €8.00' },
    hi: { birre: '🍺 बीयर और बेसिक एपेरिटिफ़', spritz: '🥂 स्प्रिट्ज़ और क्लासिक कॉकटेल — €6.00', premium: '⭐ प्रीमियम कॉकटेल — €8.00' },
    bn: { birre: '🍺 বিয়ার এবং বেসিক এপেরিটিফ', spritz: '🥂 স্প্রিৎজ এবং ক্লাসিক ককটেল — €৬.০০', premium: '⭐ প্রিমিয়াম ককটেল — €৮.০০' },
    ur: { birre: '🍺 بیئر اور بنیادی ایپریٹف', spritz: '🥂 اسپرٹز اور کلاسک کاکٹیل — €6.00', premium: '⭐ پریمیم کاکٹیل — €8.00' },
    fa: { birre: '🍺 آبجو و اپریتیف پایه', spritz: '🥂 اسپریتز و کوکتل‌های کلاسیک — €6.00', premium: '⭐ کوکتل‌های ممتاز — €8.00' }
  };
  if (typeof BAR_GROUP_TITLES !== 'undefined') {
    Object.keys(GROUP_PATCH).forEach(function (lang) {
      Object.keys(GROUP_PATCH[lang]).forEach(function (groupKey) {
        if (!BAR_GROUP_TITLES[groupKey]) BAR_GROUP_TITLES[groupKey] = {};
        BAR_GROUP_TITLES[groupKey][lang] = GROUP_PATCH[lang][groupKey];
      });
    });
    console.log('[bar_trans_patch] Merged ' + Object.keys(GROUP_PATCH).length + ' languages into BAR_GROUP_TITLES.');
  } else {
    console.warn('[bar_trans_patch] BAR_GROUP_TITLES not found — group headers were not patched.');
  }
})();
