/**
 * connect_menu_i18n.js
 * -----------------------------------------------------------------
 * Bridges i18n_patch.js + apply_i18n_patch.js into the Lago Bin menu
 * (index.html) WITHOUT hand-editing any translation content into the
 * main HTML file.
 *
 * How it works:
 *  1. Builds `translations` from window.I18N_PATCH using the original
 *     applyI18nPatch()/deepMerge() functions from apply_i18n_patch.js
 *     (exactly as those files were designed to be used).
 *  2. Automatically matches each dish's Italian name (already present
 *     in index.html as <span class="notranslate">...) against
 *     translations[lang].dishes and fills in the .sub-trans subtitle.
 *  3. Automatically maps a set of known static UI strings (tab
 *     headers, section titles, package descriptions, banners, search
 *     placeholder, wine modal, etc.) to translations[lang].
 *  4. Adds new language options to the "More Languages" dropdown for
 *     any patched language not already listed, and re-routes the
 *     ones that already exist (tr, ar, zh-CN, ja, ko) away from
 *     Google Translate and into this system.
 *
 * USAGE — add these 3 lines to index.html, right before </body>,
 * AFTER the big <script>...</script> block that defines ITEMS,
 * closeDropdown(), etc:
 *
 *   <script src="i18n_patch.js"></script>
 *   <script src="apply_i18n_patch.js"></script>
 *   <script src="connect_menu_i18n.js"></script>
 *
 * KNOWN LIMITATIONS (by design, since no content was hand-added):
 *  - Only UI strings that exist in i18n_patch.js AND have a matching
 *    element on the page get translated. Anything not covered by the
 *    patch data (e.g. dynamic popup/cart text driven by the site's
 *    own T{} object) will keep showing in whatever language was last
 *    active via the it/fr/en/de buttons.
 *  - Package accordion dish names (inside "Vedi ▾") use shortened
 *    names that don't always exactly match the patch's dish keys, so
 *    some of those may not get translated.
 *  - Elements whose text is regenerated by page's own JS on
 *    interaction (e.g. "Vedi ▾" / "Chiudi ▴" toggle) may revert to
 *    Italian/whatever language after you click them, since that text
 *    is redrawn by the site's own T{} object, not by this patch.
 * -----------------------------------------------------------------
 */
(function () {
  if (typeof window.applyI18nPatch !== 'function' || !window.I18N_PATCH) {
    console.warn('[connect_menu_i18n] i18n_patch.js / apply_i18n_patch.js not loaded before this file.');
    return;
  }

  // 1) Build the translations object exactly as the patch files intend
  var translations = window.applyI18nPatch({}, window.I18N_PATCH);
  window.LAGOBIN_TRANSLATIONS = translations; // exposed for debugging

  var LANG_META = {
    nl: { flag: '🇳🇱', name: 'Nederlands' },
    es: { flag: '🇪🇸', name: 'Español' },
    pt: { flag: '🇵🇹', name: 'Português' },
    ru: { flag: '🇷🇺', name: 'Русский' },
    pl: { flag: '🇵🇱', name: 'Polski' },
    uk: { flag: '🇺🇦', name: 'Українська' },
    ro: { flag: '🇷🇴', name: 'Română' },
    sv: { flag: '🇸🇪', name: 'Svenska' },
    da: { flag: '🇩🇰', name: 'Dansk' },
    no: { flag: '🇳🇴', name: 'Norsk' },
    fi: { flag: '🇫🇮', name: 'Suomi' },
    el: { flag: '🇬🇷', name: 'Ελληνικά' },
    cs: { flag: '🇨🇿', name: 'Čeština' },
    hu: { flag: '🇭🇺', name: 'Magyar' },
    bg: { flag: '🇧🇬', name: 'Български' },
    sk: { flag: '🇸🇰', name: 'Slovenčina' },
    hr: { flag: '🇭🇷', name: 'Hrvatski' },
    sr: { flag: '🇷🇸', name: 'Srpski' },
    sl: { flag: '🇸🇮', name: 'Slovenščina' },
    tr: { flag: '🇹🇷', name: 'Türkçe' },
    ar: { flag: '🇦🇪', name: 'العربية' },
    'zh-CN': { flag: '🇨🇳', name: '中文' },
    ja: { flag: '🇯🇵', name: '日本語' },
    ko: { flag: '🇰🇷', name: '한국어' },
    hi: { flag: '🇮🇳', name: 'हिन्दी' },
    bn: { flag: '🇧🇩', name: 'বাংলা' },
    ur: { flag: '🇵🇰', name: 'اردو' },
    fa: { flag: '🇮🇷', name: 'فارسی' },
    vi: { flag: '🇻🇳', name: 'Tiếng Việt' },
    th: { flag: '🇹🇭', name: 'ไทย' }
  };

  // Dynamic-UI keys used by the site's own T{} object (popup / cart / package
  // flow). If a language block in I18N_PATCH contains any of these top-level
  // keys, they get merged straight into T[code] automatically — no further
  // edits to this file are ever needed, only to i18n_patch.js.
  var T_KEYS = ['sub_default', 'sub_gelato', 'sub_sorbetto', 'sub_multi', 'sub_sauce', 'name_ph',
    'gusti_label', 'gusti_sel', 'gusti_hint', 'seleziona_gusto', 'preferenza_label', 'con_alcol',
    'senza_alcol', 'scegli_n', 'seleziona_ancora', 'condimento_label', 'cottura_label', 'turno_label',
    'seleziona_turno', 'nessun_articolo', 'piatti_sel', 'persona', 'conferma_aggiungi', 'conferma_btn',
    'confermato', 'modifica', 'scegli_btn', 'selezionato_btn', 'condimento_row', 'cinque_portate',
    'totale_stimato', 'nessun_risultato', 'vedi', 'chiudi', 'add_person', 'vino_prompt', 'vino_name',
    'vino_detail', 'add_vino_cart', 'vino_back'];

  // Turns a "{n}/{s}" placeholder string into a function matching T.it's
  // own function-valued entries (e.g. scegli_n:(n,s)=>`...`).
  function wrapPlaceholder(str) {
    if (typeof str !== 'string') return str;
    if (str.indexOf('{n}') === -1 && str.indexOf('{s}') === -1) return str;
    return function (n, s) {
      return str.replace(/\{n\}/g, n).replace(/\{s\}/g, s);
    };
  }
  function buildTFromPack(pack) {
    var out = {};
    T_KEYS.forEach(function (k) {
      if (pack[k] !== undefined) out[k] = wrapPlaceholder(pack[k]);
    });
    return out;
  }

  // The patch files use a different naming convention for several keys than
  // the site's own T{} object does (e.g. patch "pkg_view" = site "vedi").
  // This table lets buildTFromPack() find the right value either way.
  var ALIASES = {
    vedi: ['vedi', 'pkg_view'],
    chiudi: ['chiudi', 'pkg_close'],
    add_person: ['add_person', 'pkg_add_person'],
    conferma_aggiungi: ['conferma_aggiungi', 'pkg_confirm'],
    confermato: ['confermato', 'pkg_confirmed'],
    modifica: ['modifica', 'pkg_modify'],
    scegli_btn: ['scegli_btn', 'pkg_choose'],
    selezionato_btn: ['selezionato_btn', 'pkg_selected'],
    cinque_portate: ['cinque_portate', 'pkg_5courses'],
    nessun_articolo: ['nessun_articolo', 'cart_empty'],
    nessun_risultato: ['nessun_risultato', 'no_results'],
    totale_stimato: ['totale_stimato', 'totale'],
    conferma_btn: ['conferma_btn', 'confirm_order'],
    add_vino_cart: ['add_vino_cart', 'wine_add_cart'],
    vino_back: ['vino_back', 'wine_back'],
    condimento_row: ['condimento_row', 'condimento_label'],
    seleziona_turno: ['seleziona_turno', 'turno_hint']
  };
  function resolveVal(pack, key) {
    var candidates = ALIASES[key] || [key];
    for (var i = 0; i < candidates.length; i++) {
      if (pack[candidates[i]] !== undefined) return pack[candidates[i]];
    }
    return undefined;
  }
  function buildTFromPack(pack) {
    var out = {};
    T_KEYS.forEach(function (k) {
      var v = resolveVal(pack, k);
      if (v !== undefined) out[k] = wrapPlaceholder(v);
    });
    return out;
  }

  // Merge whatever dynamic-UI + sauce data exists into the site's own
  // T{} / SAUCE_TRANS objects, for every patched language, once.
  if (typeof T === 'object' && typeof SAUCE_TRANS === 'object') {
    Object.keys(translations).forEach(function (code) {
      var pack = translations[code];
      var tAdd = buildTFromPack(pack);
      if (Object.keys(tAdd).length) T[code] = tAdd;
      if (pack.sauces) {
        Object.keys(pack.sauces).forEach(function (sKey) {
          if (!SAUCE_TRANS[sKey]) SAUCE_TRANS[sKey] = {};
          SAUCE_TRANS[sKey][code] = pack.sauces[sKey];
        });
      }
    });
  }

  // Gelato flavor translations — merged directly into GELATO_FLAVORS objects;
  // the site's own flavorLabel()/renderInlineGelato() already read f[currentLang].
  if (typeof GELATO_FLAVORS !== 'undefined') {
    Object.keys(translations).forEach(function (code) {
      var pack = translations[code];
      if (!pack.flavors) return;
      GELATO_FLAVORS.forEach(function (f) {
        var val = pack.flavors[f.it];
        if (val) f[code] = val;
      });
    });
  }
  if (typeof STATIC_BUCKET_MAP === 'object') {
    Object.keys(translations).forEach(function (code) {
      var pack = translations[code];
      if (pack.course_menu || pack.course_dolci || pack.course_gelato || pack.course_bevande) {
        STATIC_BUCKET_MAP[code] = {
          menu: pack.course_menu || STATIC_BUCKET_MAP.it.menu,
          dolci: pack.course_dolci || STATIC_BUCKET_MAP.it.dolci,
          gelato: pack.course_gelato || STATIC_BUCKET_MAP.it.gelato,
          bevande: pack.course_bevande || STATIC_BUCKET_MAP.it.bevande
        };
      }
    });
  }

  // Turno (course-order) labels — patch stores these as a 4-item array
  if (typeof TURNO_LABELS === 'object') {
    Object.keys(translations).forEach(function (code) {
      var pack = translations[code];
      if (Array.isArray(pack.turno) && pack.turno.length === 4) {
        TURNO_LABELS[code] = pack.turno;
      }
    });
  }

  // NOTE: cart/overlay section headers (courseLabel, ALA_CARTA_LABEL) are
  // intentionally left in Italian per restaurant preference — the cart is
  // shown to kitchen/waiter staff and should stay consistent in Italian.

  // Cottura (doneness level) labels — same pattern as turno, but the site
  // has no built-in translation slot for these at all, so we build one.
  var COTTURA_IT = ['🔴 Al Sangue', '🟠 Blue', '🟡 Media Cottura', '✅ Ben Cotto'];
  var COTTURA_LABELS = {};
  Object.keys(translations).forEach(function (code) {
    var pack = translations[code];
    if (Array.isArray(pack.cottura) && pack.cottura.length === 4) {
      COTTURA_LABELS[code] = pack.cottura;
    }
  });

  // Package accordion section headers (Antipasti / Primi Piatti / Secondi
  // Piatti / Piatti a scelta) — hardcoded Italian in the site, never
  // translated even by it/fr/en/de. Map each to the matching patch key.
  var SECTION_KEY_MAP = {
    'Antipasti': 'cat_antipasti',
    'Primi Piatti': 'cat_primi',
    'Secondi Piatti': 'cat_secondi',
    'Piatti a scelta': 'pkg_section_scelta'
  };
  function translateSectionHeads() {
    var pack = translations[currentLang];
    if (!pack) return;
    document.querySelectorAll('.pkg-section-head').forEach(function (el) {
      var raw = el.textContent.replace('📍', '').trim();
      var key = SECTION_KEY_MAP[raw];
      var val = key && pack[key];
      if (val) el.textContent = '📍 ' + val;
    });
  }
  // Some package-accordion dish names are shortened/reworded versions of
  // the full à la carte names, so they need to be mapped before lookup.
  var PKG_DISH_ALIAS = {
    'Prosciutto di Parma': 'Prosciutto di Parma con Melone o Grana',
    'Agnello alla Griglia': 'Costine di Agnello alla Griglia'
  };
  function safeRun(fn) {
    try { fn(); } catch (e) { console.warn('[connect_menu_i18n] step failed, continuing:', e); }
  }

  function translateWineNames() {
    var pack = translations[currentLang];
    if (!pack) return;
    if (pack.wines) {
      document.querySelectorAll('.vini-row span[data-it]').forEach(function (el) {
        var it = el.getAttribute('data-it');
        var val = pack.wines[it];
        if (val) el.textContent = val;
      });
    }
    if (pack.wine_full_list) {
      var btn = document.querySelector('.vini-modal-btn.primary');
      if (btn) btn.textContent = pack.wine_full_list;
    }
  }
  if (typeof openViniModal === 'function') {
    var _origOpenViniModal = openViniModal;
    openViniModal = function () {
      _origOpenViniModal.apply(this, arguments);
      translateWineNames();
    };
  }
  function translatePkgDishNames() {
    var pack = translations[currentLang];
    if (!pack) return;
    var dishes = pack.dishes || {};
    var kids = pack.kids_dishes || {};
    document.querySelectorAll('.pkg-dish-name').forEach(function (el) {
      var existing = el.querySelector('.pkg-sub-trans');
      if (existing) existing.remove();
      var it = '';
      for (var i = 0; i < el.childNodes.length; i++) {
        var node = el.childNodes[i];
        if (node.nodeType === 3 && node.textContent.trim()) { it = node.textContent.trim(); break; }
      }
      if (!it) return;
      var lookupKey = PKG_DISH_ALIAS[it] || it;
      var subText = dishes[lookupKey] || kids[it];
      if (subText) {
        var sub = document.createElement('div');
        sub.className = 'sub-trans pkg-sub-trans notranslate';
        sub.style.display = 'block';
        sub.style.marginTop = '6px';
        sub.textContent = subText;
        el.appendChild(sub);
      }
    });
  }
  function translatePkgSauceChips() {
    var pack = translations[currentLang];
    if (!pack || !pack.sauces) return;
    document.querySelectorAll('.pkg-sauce-chips .chip').forEach(function (btn) {
      var it = btn.textContent.trim();
      var val = pack.sauces[it];
      if (val) btn.textContent = val;
    });
  }
  function translateCotturaChips() {
    var labels = COTTURA_LABELS[currentLang];
    if (!labels) return;
    document.querySelectorAll('.cottura-chip').forEach(function (btn) {
      var m = (btn.getAttribute('onclick') || '').match(/popupSetCottura\(\d+,'([^']+)'\)/);
      if (!m) return;
      var itText = m[1].replace(/\\'/g, "'");
      var idx = COTTURA_IT.indexOf(itText);
      if (idx > -1 && labels[idx]) btn.textContent = labels[idx];
    });
  }
  // Wrap the site's own render functions so these two extra translation
  // passes run every time the popup / package accordion redraws.
  if (typeof renderPopupPersons === 'function') {
    var _origRenderPopupPersons = renderPopupPersons;
    renderPopupPersons = function () {
      _origRenderPopupPersons.apply(this, arguments);
      translateCotturaChips();
    };
  }
  if (typeof renderPkgPersons === 'function') {
    var _origRenderPkgPersons = renderPkgPersons;
    renderPkgPersons = function () {
      _origRenderPkgPersons.apply(this, arguments);
      translateSectionHeads();
      translatePkgDishNames();
      translatePkgSauceChips();
    };
  }

  // 2) Map of static UI selectors -> patch key (only applied when both exist)
  var TAB_KEYS = {
    antipasti: 'cat_antipasti',
    primi: 'cat_primi',
    secondi: 'cat_secondi',
    contorni: 'cat_contorni',
    dolce: 'cat_dolce',
    gelato: 'cat_gelato',
    bar: 'cat_bar'
  };

  function setText(selector, val) {
    if (val === undefined || val === null) return;
    var el = document.querySelector(selector);
    if (el) el.textContent = val;
  }
  function setAllText(selector, val) {
    if (val === undefined || val === null) return;
    document.querySelectorAll(selector).forEach(function (el) { el.textContent = val; });
  }
  function setPlaceholder(selector, val) {
    if (val === undefined || val === null) return;
    var el = document.querySelector(selector);
    if (el) el.placeholder = val;
  }
  function setCatTitleText(tabId, val) {
    if (val === undefined || val === null) return;
    var el = document.querySelector('#sec-' + tabId + ' .cat-title');
    if (!el) return;
    for (var i = 0; i < el.childNodes.length; i++) {
      if (el.childNodes[i].nodeType === 3 && el.childNodes[i].textContent.trim()) {
        el.childNodes[i].textContent = val;
        return;
      }
    }
    el.textContent = val; // fallback if no leading text node found
  }

  function normKey(s) {
    return (s || '').normalize ? (s || '').normalize('NFC').trim() : (s || '').trim();
  }
  function extractItalianName(nameEl) {
    var nt = nameEl.querySelector('.notranslate:not(.sub-trans)');
    if (nt) return nt.textContent.trim();
    var clone = nameEl.cloneNode(true);
    var sub = clone.querySelector('.sub-trans');
    if (sub) sub.parentNode.removeChild(sub);
    var pkgSub = clone.querySelector('.pkg-sub-trans');
    if (pkgSub) pkgSub.parentNode.removeChild(pkgSub);
    return clone.textContent.trim();
  }
  function applyDishSubtitles(pack) {
    var dishes = pack.dishes || {};
    var normDishes = {};
    Object.keys(dishes).forEach(function (k) { normDishes[normKey(k)] = dishes[k]; });
    document.querySelectorAll('.item-name').forEach(function (nameEl) {
      var subEl = nameEl.querySelector('.sub-trans');
      if (!subEl) return;
      var itName = extractItalianName(nameEl);
      var txt = dishes[itName] || normDishes[normKey(itName)];
      if (txt) {
        subEl.textContent = txt;
        subEl.style.display = 'block';
        subEl.classList.add('notranslate');
      } else {
        subEl.textContent = '';
        subEl.style.display = 'none';
        subEl.classList.remove('notranslate');
      }
    });
  }

  function applyStaticUi(pack) {
    setText('.header .subtitle', pack.subtitle);
    setPlaceholder('#searchInput', pack.search_ph);

    Object.keys(TAB_KEYS).forEach(function (tabId) {
      var key = TAB_KEYS[tabId];
      var val = pack[key];
      if (val === undefined) return;
      document.querySelectorAll('.tab-btn[onclick*="\'' + tabId + '\'"]').forEach(function (btn) {
        btn.textContent = val;
      });
      setCatTitleText(tabId, val);
    });
    setText('#sec-secondi .cat-title span', pack.secondi_sub);

    setText('.dolce-banner h3', pack.dolce_banner_title);
    setText('.dolce-banner p', pack.dolce_banner_sub);
    setText('#item-gelato .item-desc', pack.gelato_desc);
    setText('#item-sorbetto .item-desc', pack.sorbetto_desc);

    // quick cards: 1=wine, 2=dolci, 3=bar
    setText('.quick-card:nth-child(1) .card-text > span:first-child', pack.card_wine);
    setText('.quick-card:nth-child(1) .card-label', pack.card_wine_sub);
    setText('.quick-card:nth-child(2) .card-text > span:first-child', pack.card_dolce);
    setText('.quick-card:nth-child(2) .card-label', pack.card_dolce_sub);
    setText('.quick-card:nth-child(3) .card-text > span:first-child', pack.card_bar);
    setText('.quick-card:nth-child(3) .card-label', pack.card_bar_sub);

    setText('.cart-fab > span:not(.cart-badge)', pack.order_btn);
    setText('.cart-title', pack.cart_title);
    setText('#waiter-btn', pack.waiter_btn);

    setText('.overlay-sub', pack.overlay_sub);
    setText('.overlay-close', pack.overlay_close);
    setText('.overlay-note', pack.overlay_note);

    // Set menu packages, in DOM order: lago_bin, gastro, degu, bambini
    setText('.pkg-item:nth-of-type(1) .pkg-desc', pack.pkg_lago_desc);
    setText('.pkg-item:nth-of-type(2) .pkg-desc', pack.pkg_gastro_desc);
    setText('.pkg-item:nth-of-type(3) .pkg-desc', pack.pkg_degu_desc);
    if (pack.pkg_degu_warn) {
      var warnEl = document.querySelector('.pkg-item:nth-of-type(3) div[style*="color:#b31e1e"]');
      if (warnEl) warnEl.textContent = pack.pkg_degu_warn;
    }
    setText('.pkg-item:nth-of-type(4) .pkg-desc', pack.pkg_bambini_desc);

    if (pack.note_box) {
      setAllText('.note-box-text', pack.note_box);
      setText('.footer .note', pack.note_box);
    }

    // Wine modal
    setText('.vini-modal-title', pack.wine_title || pack.card_wine);
    setText('.vini-modal-sub', pack.wine_sub);

    // Small extras present under the patch's own naming
    setText('.popup-cancel', pack.cancel);
    setText('.cart-total > span:first-child', pack.cart_total);
  }

  // CRITICAL FIX: the site's own applyLang(lang) wipes EVERY .sub-trans box
  // on the whole page whenever it runs with a language it doesn't know
  // (any of our 30 patched languages), because it looks for a matching
  // data-<lang> attribute that only exists for it/fr/en/de. applyLang()
  // gets called automatically e.g. every time the wine modal opens
  // (openViniModal -> applyLang(currentLang)), silently erasing every dish
  // subtitle on the page. We intercept it here and, for our languages,
  // re-apply our own (correct) subtitles instead of letting it wipe them.
  if (typeof applyLang === 'function') {
    var _origApplyLang = applyLang;
    applyLang = function (lang) {
      if (translations[lang]) {
        applyDishSubtitles(translations[lang]);
        return;
      }
      _origApplyLang(lang);
    };
  }

  // 3) The actual language switch used by dropdown items
  window.setPatchLang = function (code) {
    if (typeof closeDropdown === 'function') closeDropdown();
    document.querySelectorAll('.lang-btn').forEach(function (b) { b.classList.remove('active'); });
    var meta = LANG_META[code];
    var btnLabel = document.getElementById('translateBtn');
    if (btnLabel) btnLabel.textContent = meta ? meta.flag + ' ' + meta.name + ' ▾' : '🌐 More Languages ▾';

    // If Google Translate was previously engaged for another language, disengage it
    var sel = document.querySelector('.goog-te-combo');
    if (sel && sel.value !== '') {
      document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
      sel.value = '';
      sel.dispatchEvent(new Event('change'));
    }

    var pack = translations[code] || {};
    safeRun(function () { applyDishSubtitles(pack); });
    safeRun(function () { applyStaticUi(pack); });

    // Switch the site's own language state so popup/cart/package text (T{})
    // and sauce/flavor labels use this language too — with automatic
    // per-key fallback to Italian for anything not yet translated.
    if (typeof currentLang !== 'undefined') currentLang = code;
    safeRun(function () { if (typeof refreshDyn === 'function') refreshDyn(); });
    safeRun(function () { translateCotturaChips(); });
    safeRun(function () { translateSectionHeads(); });
    safeRun(function () { translatePkgDishNames(); });
    safeRun(function () { translatePkgSauceChips(); });
    safeRun(function () { translateWineNames(); });

    // Defensive re-pass: reported symptom was "needs to be selected twice" —
    // some elements weren't ready on the very first synchronous pass. Redo
    // everything a moment later so a second click is never needed.
    setTimeout(function () {
      if (currentLang !== code) return; // user switched language again meanwhile
      safeRun(function () { applyDishSubtitles(pack); });
      safeRun(function () { applyStaticUi(pack); });
      safeRun(function () { if (typeof refreshDyn === 'function') refreshDyn(); });
      safeRun(function () { translateCotturaChips(); });
      safeRun(function () { translateSectionHeads(); });
      safeRun(function () { translatePkgDishNames(); });
      safeRun(function () { translatePkgSauceChips(); });
      safeRun(function () { translateWineNames(); });
    }, 200);
  };

  // 4) Rebuild the "More Languages" dropdown cleanly, grouped and ordered
  var dropdown = document.getElementById('langDropdown');
  if (!dropdown) return;

  var EUROPE_ORDER = ['nl', 'es', 'pt', 'ru', 'pl', 'uk', 'ro', 'sv', 'da', 'no', 'fi', 'el', 'cs', 'hu',
    'bg', 'sk', 'hr', 'sr', 'sl', 'tr'];
  var WORLD_ORDER = ['ar', 'zh-CN', 'ja', 'ko', 'hi', 'bn', 'ur', 'fa', 'vi', 'th'];

  dropdown.innerHTML = '';

  function addSection(title, codes) {
    var available = codes.filter(function (c) { return translations[c]; });
    if (!available.length) return;
    var sec = document.createElement('div');
    sec.className = 'lang-dropdown-section';
    sec.textContent = title;
    dropdown.appendChild(sec);
    available.forEach(function (code) {
      var meta = LANG_META[code];
      var item = document.createElement('div');
      item.className = 'lang-dropdown-item';
      item.textContent = meta ? meta.flag + ' ' + meta.name : code;
      item.addEventListener('click', function () { window.setPatchLang(code); });
      dropdown.appendChild(item);
    });
  }

  addSection('🇪🇺 Europe', EUROPE_ORDER);
  addSection('🌍 World', WORLD_ORDER);
})();
